### ISSUE TITLE
Post CSS only?

### ISSUE THREAD

**Issue by abstracthat** [corysimmons/lost#102]
I can appreciate moving to a single code base (instead of supporting Stylus, Sass, and Less), but I felt the workflow was a lot cleaner with the dedicated Stylus library (at least for a Stylus designer). I'm sort of left figuring out this PostCSS stuff. And now all of this `lost-` prefixed rules instead of the  clean Stylus mixins. Would it be possible to make a auto-build port of this or something? Or I guess I'm just complaining here.

**Comment by corysimmons** [comment]
I understand that and agree a bit - it is definitely easier to toss a `.styl` into your workflow than to be forced to use something like Gulp or Grunt. I'm planning on porting Lost to a Stylus plugin (if I can figure it out) like they've done with Autoprefixer - but this will be a ways off.

**Comment by abstracthat** [comment]
I do use Gulp for static sites but I just like the Stylus mixin workflow better. I think I might stick with the old version or maybe just go back to Jeet for now. I like what you are doing with this project but I feel a bit too 'out-of-my-element' now and don't really have the time to give this all a thorough go.

**Comment by corysimmons** [comment]
No problem. I understand. Lost 5.1.6 was the last version with Stylus in it and is still a lot better than other grids imo.

**Comment by corysimmons** [comment]
Why not grab it and create your own repo? I can link to it so others with your opinion can stay up-to-date on it.

**Comment by IbnSaeed** [comment]
I had already forked it before lost was ported to use Postcss

Here is the link:
https://github.com/IbnSaeed/lost

**Comment by custa1200** [comment]
For the record I have been using the PostCSS port along with Stylus and Rupture successfully over the past few days. I'm finding it to be quite a good experience with the markup but I guess I have never really been a fan of non braced non semi colon markup so I still use traditional looking CSS in my styl files.

**Comment by corysimmons** [comment]
@custa1200 If you're using traditional CSS syntax why not just use CSS?

**Comment by corysimmons** [comment]
@IbnSaeed Do you plan to maintain/update your fork? If not, people can still access the codebase from https://github.com/corysimmons/lost/tree/6a3be90d6cba3bb70121c26099f41fb0bce059ad forever.

**Comment by corysimmons** [comment]
Closing as this isn't really an issue so much as a complaint. :D

**Comment by corysimmons** [comment]
@IbnSaeed Issues are closed on your fork

**Comment by IbnSaeed** [comment]
@corysimmons i have opened the issues

**Comment by abstracthat** [comment]
For anyone intersted... I made a custom fork with just the basic mixins (clearfix, center, column, offset, and move) and published to npm under happy-grid.

https://github.com/abstracthat/happy-grid/

**Comment by custa1200** [comment]
I use it to leverage the power of variables, mixins and other functions that Stylus provides. I just hate the preferred brace-less, semicolon-less style.

**Comment by corysimmons** [comment]
https://twitter.com/mdo/status/591364406816079873 Booya. Even Bootstrap is getting ported to PostCSS. Y'all cats better get hip to this Gulp stuff. =)

**Comment by corysimmons** [comment]
@custa1200 If you like curly braces/semi-colons you should use SCSS.

**Comment by flip4bytes** [comment]
@custa1200 I personally switched from CSS to use Stylus a few years back and it was weird at first, but I could never go back now. I use Stylus without braces and semi-colons, but still use colons. It's considered good practice to still use colons to break it up. Same as using $ for variables in stylus even though they aren't really needed.

But @CorySimmons this is a first.. Actually seeing you trying to convince someone off of Stylus! What are you thinking?? Haha I kid :x

**Comment by corysimmons** [comment]
haha I know, I said it to myself immediately after hitting "Comment". Don't want people polluting Stylus eco-system with curly braces, especially when I think all that flexibility is about to get banned.

**Comment by custa1200** [comment]
The ability to use braces and semi colons is going to go away from Stylus??? That would be rubbish.

**Comment by corysimmons** [comment]
I'm not 100% sure but I think everyone in the Stylus community wants to make Stylus less flexible so every other dev isn't developing it their own way. Consistency is important, especially when you get into libraries and such.

**Comment by custa1200** [comment]
Good thing PostCSS has come along and everybody can get back to consistently using braces and semi-colons :P

**Comment by flip4bytes** [comment]
Braces and semi-colons need to die. And PostCSS doesn't meant Braces and Semi-colons, you can use PostCSS with Stylus, any preprocessor. It's what autoprefixer is built in. Just because you can use vanilla CSS with PostCSS doesn't mean you should, braces and semi-colons are a total waste of time.
