### ISSUE TITLE
Clarify lost-waffle description in docs

### ISSUE THREAD

**Issue by mmarol** [corysimmons/lost#104]
The description of `fraction - This is a simple fraction of the containing element's width/height.` lead me to think that `lost-waffle: 1/3;` would make the elements in the grid would have a width of 1 and a height of 3, but it just meant that both the width and the height of the element are 1/3 the container's width and height.
Perhaps you could change the description to:
`fraction - This is a simple fraction of the containing element's width and height.`

**Comment by corysimmons** [comment]
:+1:

**Comment by corysimmons** [comment]
Done. Thanks for pointing this out.
