### ISSUE TITLE
lost-waffle additional functionality

### ISSUE THREAD

**Issue by mmarol** [corysimmons/lost#105]
Would it be possible to add functionality to specify 2 fractions in `lost-waffle`, one for `row` and one for `column`? Currently, it seem that I can do that by specifying `lost-row` and then `lost-column` (also, weirdly only in that order), but it would be great if you could do that within `lost-waffle`.

**Comment by corysimmons** [comment]
Sorry, there's no way to do this that I could think of. You're doing it the right way with `lost-row` and `lost-column`. :)
