### ISSUE TITLE
Add instructions on usage with Sprockets and/or Rails

### ISSUE THREAD

**Issue by lightyrs** [corysimmons/lost#106]
I love this grid but I'm stuck in Rails-land and am very confused on how to run postcss plugins, lost-grid specifically, with Sprockets/Rails.  If you have any idea of how to do this, some documentation would be great.  If not, I will attempt to figure it out (but most likely end up having to wait until some Sprockets genius comes along with a plugin).

Thanks for the great work!

**Comment by corysimmons** [comment]
*sigh* I knew this day would come.

I don't have a good answer for it. I've heard of a lot of people migrating from Sprockets to a task runner, and it's probably the best idea, but if you're stuck in Sprockets then I'm sure there's a way to expose PostCSS plugins to Rails on a per-plugin basis.

I know @ai has done it with https://github.com/ai/autoprefixer-rails but I'm not an amazing JS or Ruby dev so I don't even know where I'd start exposing Lost to that.

If you want to be my savior and take up this project I'd totally love you forever and link to you project with installation instructions and the whole 9 yards.

In the meantime, I can just heartily hope that everyone migrates from Sprockets to a task runner within Rails. There are plenty of articles on it out there.

**Comment by lightyrs** [comment]
Thanks for the quick reply.

I am happy to give this a try, however, I am wondering what you feel is the best method for getting a compiled version of lost.  Browserify?

**Comment by corysimmons** [comment]
I'm not familiar with Browserify either.

**Comment by lightyrs** [comment]
I'll see what I can come up with.  Thanks for the quick replies and the awesome grid.

**Comment by corysimmons** [comment]
No problem. Thanks for looking into it! :)

**Comment by ai** [comment]
Here is a Autoprefixer’s code, which buid standalone version for Rails ExecJS: https://github.com/postcss/autoprefixer-core/blob/master/gulpfile.js#L44

**Comment by corysimmons** [comment]
Until someone develops an adapter for Rails (something I'm not capable of doing) my only advice is to convince your team to switch from Asset Pipeline to Gulp. Closing.
