### ISSUE TITLE
How to put an element vertically centered

### ISSUE THREAD

**Issue by imrefazekas** [corysimmons/lost#108]
Hello,

I would like to centre vertically the divs containing "Hello4" and "Hello5" within the row they have been put:
https://www.dropbox.com/s/e1pi9qc545qne9n/IMG_0081.PNG?dl=0

How can I do such thing?
I'm using the @lost flexbox flex; and tried every combination crossed my mind without any luck.

	.half-screen
		.column-third.offset-third
			.ikon
				text Hello4
		.column-third
			.ikon
				text Hello5

with css:

	.half-screen{
		lost-row: 1/2 0;
	}
	.column-third {
		lost-column: 1/3;
	}
	.offset-third:first-child {
		lost-offset: -1/6;
	}
	.ikon {
		width: 3rem;
		height: 3rem;
		lost-align: center;
		lost-center: 3rem flex;
	}

Thank in advance!

**Comment by corysimmons** [comment]
What markup does

```
.half-screen
    .column-third.offset-third
        .ikon
            text Hello4
    .column-third
        .ikon
            text Hello5
```

produce?

**Comment by imrefazekas** [comment]
Just found the answer. The following lines were success:

	.half-screen{
		lost-row: 1/2 0;
	}
	.column-third {
		lost-column: 1/3;
		lost-align: center;
	}
	.offset-third:first-child {
		lost-offset: -1/6;
	}

Now everything is in the middle vertically. 

BTW, how would you manage to mix Lost with Stylus? This CSS is bugging me a little bit...

**Comment by corysimmons** [comment]
Awesome, glad you got it.

I use Stylus with Lost. Here's an example Gulpfile that works: https://github.com/corysimmons/lost/blob/gh-pages/gulpfile.js

**Comment by imrefazekas** [comment]
You rock! Thank you!

**Comment by corysimmons** [comment]
No problem. Hope you're enjoying Lost. Tell a friend. =)

**Comment by imrefazekas** [comment]
The moment I switched to styles, everything crashed ....

**Comment by corysimmons** [comment]
Can you post your gulpfile and such?

**Comment by imrefazekas** [comment]
My stylus starts like this:

	@import "lost.css"
	body
		width 100%
		height 100%
		margin 0
		padding 0
		font-size calc( 20px + (8) * ( (100vw - 36em) / (120em - 36em) ))

In lost.css as you mentioned:

	@lost gutter 10px;
	@lost flexbox flex;

Gulp copied from you:

	global.gulp.task(taskName, function () {
		return global.gulp.src( options.sourceFolder + '/styles/' + options.pageName + '.styl')
			.pipe( global.plugins.plumber() )
			.pipe( global.plugins.sourcemaps.init() )
			.pipe( global.plugins.stylus() )
			.pipe( global.plugins.postcss([ global.lost() ]))
			.pipe( global.plugins.autoprefixer() )
			.pipe( global.plugins.sourcemaps.write('./') )
			.pipe( global.gulp.dest( options.destinationFolder + '/css' ))
			.pipe( global.plugins.livereload() );
	});

**Comment by corysimmons** [comment]
What's the error?

**Comment by corysimmons** [comment]
Bring this to https://gitter.im/corysimmons/lost ?

**Comment by imrefazekas** [comment]
Result CSS has this as first line:

        @import './lost.css';

**Comment by imrefazekas** [comment]
Sure ....
