### ISSUE TITLE
Disable cycle by default?

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/lost#109]
`cycle` by default is neat but it causes some problems. Take the following example...

The markup might look like this:

```html
<section>
  <div class="quarter">1</div>
  <div class="half">
    <div class="half__child">2</div>
    <div class="half__child">3</div>
  </div>
  <div class="quarter">4</div>
</section>
```

The Stylus might look like this:

```stylus
section
  lost-utility: clearfix

.quarter
  lost-column: 1/4

.half
  lost-column: 1/2

.half__child
  lost-column: 1/2
```

The result seems like it should be:

```
1 | 2 3 | 4
```

But instead, it produces:

```
1 | 4 | 2 3
```

It floats the last element of a row to the right to prevent some subpixel rounding errors which are rare so I'm removing this.

It also messes with `:nth-child` to do some stuff automatically for the user which results in this screwy layout.

I think the best approach would be to remove automatic `cycle` and force the user to enable it manually if they want it (block lists only).

This would make Lost work better as a general layout tool rather than simple a block list generator.

Thoughts?

**Comment by irisli** [comment]
I think lost would be more flexible if cycle were disabled by default.

Users could add `cycle` to the `lost-column` to if they know all the items are going to be the same size. This is a more verbose but it is necessary because ultimately, the user will know best which elements are on the right side of the grid.

I think bourbon neat and susy also does not automatically include the omega/last since it doesn't work for mixed size blocks. I prefer this explicit method of removing the margins.

As for pixel rounding errors, maybe lost could use -100% margins (http://susydocs.oddbird.net/en/latest/toolkit/#isolate).

**Comment by corysimmons** [comment]
I don't think isolate works for multiple rows. For instance, it will work for the first 4 out of 4 elements, but 5 and 6 won't work. Maybe I'm wrong about this. Also I don't think the subpixel stuff is a big issue. I'll have to look deeper into it but I think that the subpixel stuff is negated by calc() grid-dom.

**Comment by flip4bytes** [comment]
Definitely leave the option to do autocycling at the very least, because most of my grids are just normal 1/2, 1/3, 1/4, 1/5, etc. sure, occasionally I'll do some weird mixes like what you mentioned above, but for example, a site I am working on now, I have gotten away with auto cycling and it has just been convenient. Not having to uncycle when hitting breakpoints and then re-cycle and all of that. It was a pain in the butt to do that with Jeet. I got spoiled by the auto cycling. Can't the user just override the cycle when they have a scenario like the one above rather than completely disabling cycling from the get-go?

**Comment by corysimmons** [comment]
Without auto `cycle` you at least wouldn't have to `uncycle` like you do in Jeet.

**Comment by flip4bytes** [comment]
@corysimmons ah yes, you're still resetting it auto `cycle` or not. Makes sense. Is there a way to have it just auto cycle but allow us to override the cycle? So leave it auto cycle but if we need a specific cycle then just throw in the cycle variable and it'll clear out the auto and override it?

**Comment by corysimmons** [comment]
Yeah I could set it to be `lost-column: 1/3 0` or something, but I think it's less intuitive than asking the user to add `cycle` if they need it and just disable it by default.

**Comment by flip4bytes** [comment]
Enable/Disable by default should really be determined by thinking "what is the most used functionality?" to me it sounds the example above is more of a use-case scenario and not so much the norm. But I could be wrong. Just saying that from how I have experienced it through building a site thus far. If the user has it enabled though, it's easy enough to override it though, right? Or would the user have to actually reset it first and then set the proper cycle?

**Comment by corysimmons** [comment]
I think what I'm going to do is add a global setting that let's people pick if they want this functionality globally. If so, they can enable it. By default, I'll disable it since I think it seems more intuitive to set `cycle` manually if you need it. This would let Lost be more of a layout system (uneven sized columns everywhere that add up to `1`).

**Comment by flip4bytes** [comment]
Cycle lives on! :D Dammit Cory, you shouldn't have spoiled us with it doing it automatically on the basic cases because now it feels like we are losing something, when in reality, it just has to be done :p

**Comment by corysimmons** [comment]
^ this

**Comment by pikeas** [comment]
Principle of least surprise. No cycle by default. Can you print a warning if the row fractions don't add up?

Also, cycle docs could use some additional explanation. I had to read through the JS and tinker a bit to understand (I think) what cycle does.

**Comment by corysimmons** [comment]
@pikeas I'm not sure how I would print a warning. Like... I can add that logic in there, but where do I return it?

```css
.foo {
  lost-column: 1/3; /* Items in this row are greater than 1 */
}
```

?

I don't really like the look of it.

Add a new issue for cycle docs plz.

**Comment by pikeas** [comment]
Re: warning - Lost is a PostCSS plugin - print a warning during processing. :-)

**Comment by corysimmons** [comment]
Oh snap https://github.com/postcss/postcss/blob/master/API.md#warning-class

**Comment by corysimmons** [comment]
Actually I can't think of a way to implement this since there's no way to tell which selectors they'd be using. For instance:

```stylus
.foo
  lost-column: 1/2

.bar
  lost-column: 1/2

.baz
  lost-column: 1/2
```

No way to tell which of those 2 are supposed to be in a container or if all 3 are.

**Comment by corysimmons** [comment]
After a lot of experimenting I've changed my mind on this. I think `cycle` *will* be enabled by default. It feels better.

**Comment by flip4bytes** [comment]
woohoo!

**Comment by corysimmons** [comment]
This isn't a breaking change - just a new feature - so it will still be v6.

**Comment by corysimmons** [comment]
You can use it globally or on a local level like so:

```html
<section>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</section>
```

```css
section {
  lost-utility: clearfix;
}

div {
  lost-column: 1/4;
}

div:nth-child(2) {
  lost-column: 1/2 0;
}
```

Result:
```
[ 1 ] [    2    ] [ 3 ]
```

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/fc7748a4c7d8740fa4004c147489998b53ab8ac5
