### ISSUE TITLE
Lost doesn't remove margin right 

### ISSUE THREAD

**Issue by snowe2010** [corysimmons/lost#111]
From the documentation:
```
Every element gets a float: left and margin-right: gutter applied to it except the last element in the row. Lost will automatically detect the last item in a row (based on the denominator you passed) and apply a margin-right: 0 to it by default.
```

Yet with this simple css

```
nav {
    lost-utility: clearfix;
    lost-column: 1/3;
}

div {
    lost-column: 2/3 0;
}

body {
    lost-utility: edit;
}
```

and this html:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="description" content="description of your site">
    <meta name="author" content="author of the site">
    <title>/index.html</title><link rel='stylesheet' href='css\test.css' />
  </head>
  <body>
    <nav>
      <h3>Tyler Thrailkill</h3>
      <p>Don't look back</p><a href="/blog">blog</a><a href="/">home</a><a href="/tutorials">tutorials</a>
    </nav>
    <div class="posts">
      <div class="post"></div>
      <h2><a href="\posts\test.html">Hello world</a></h2>
      <date>1/2/2015</date>
      <p>I talk about nothing</p>
    </div><script src='js\main.js'></script>
  </body>
</html>
```

my page looks like this:
![forgithub](https://cloud.githubusercontent.com/assets/1534535/7359083/c769ef1e-ecf7-11e4-8eb6-f6faa9201f1c.png)

When I examine the css, it still has a margin-right of 30px on the 2/3 div. Shouldn't that be 0px?

**Comment by corysimmons** [comment]
Yes, I'm currently figuring out a fix for this over here https://github.com/corysimmons/lost/issues/109

**Comment by snowe2010** [comment]
I looked over that thread before posting this one, but I wasn't sure if it was the same issue. What can I do to fix this for right now, if there even is a fix. I'm kinda new to a lot of this stuff. Don't even know what cycle is.

**Comment by corysimmons** [comment]
You can manually add `margin-right: 0` to that element.

`cycle` basically sets `nth-child(Xn)` to `margin-right: 0`.

I'll try to get this fixed tonight.

**Comment by snowe2010** [comment]
Cool that worked. I'll keep it like this until you update the library. Thanks for the help!

**Comment by corysimmons** [comment]
Library updated but now that I'm re-reading this issue, I don't think it's the same thing. I think your code might be a bit broken. Here's what I would do:

```html
<section>
  <nav>...</nav>
  <div class="posts">...</div>
</section>
```

```css
section {
  lost-utility: clearfix;
}

nav {
  lost-column: 1/3;
}

.posts {
  lost-column: 2/3;
}
```

**Comment by snowe2010** [comment]
Ok, so I think maybe I'm misunderstanding how to use Lost properly. 

When I use the code you've posted (in other words putting the nav and div in a <section> tag) the css works. As soon as I make nav and div direct children of <body> it reverts to the margin on both tags.

**Comment by corysimmons** [comment]
Lost operates using a lot of `nth-child` stuff, so when it's a direct child of `<body>` things like `<script>`, etc. get counted as children. By starting your code in some sort of wrapper (just not `body`) you fix this.

**Comment by snowe2010** [comment]
Ah I understand. Great well that fixed my issue so far!
