### ISSUE TITLE
Browser support docs - add flexbox section

### ISSUE THREAD

**Issue by pikeas** [corysimmons/lost#113]
The browser support section should list supported browsers for the flexbox mode, linking to any necessary polyfills for IE 10/9/8.

**Comment by corysimmons** [comment]
There are no polyfills for Flexbox that I know of. Flexie is broken and the rework of it is a dead project.

**Comment by pikeas** [comment]
Bummer, that was my impression as well.

I think we're on the same page about the core point: browser compatibility section should have a clear explanation:

    calc mode: works in Chrome X+, IE X+ with polyfill Y, ..
    flexbox mode: <similar>

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/b6f5e619098f3340e093649baccd645d7d71fbb7
