### ISSUE TITLE
Problem with masonry-column and lostMasonryColumnGutterUnit

### ISSUE THREAD

**Issue by jackhogg** [corysimmons/lost#115]
When attempting to use the masonry-column function, I continue running into an error where the gutter unit "isn't defined", regardless of the unit of measurement used for the gutter. This also occurs regardless of whether I'm defining the gutter width through the column settings, or separately, as a variable definition.

**Comment by corysimmons** [comment]
Okay, will fix today.

**Comment by corysimmons** [comment]
Fixed. Was missing a comma in var declarations. :)
