### ISSUE TITLE
Trying Lost

### ISSUE THREAD

**Issue by martinsmith** [corysimmons/lost#116]
Hi there,
Is there any way (instructions) to take lost for a spin without Gulping and Grunting?

Sorry, should mention i'm using CodeKit which provides download via Bower, but how do I then link it all up :/

Thanks

Martin

**Comment by corysimmons** [comment]
There is no way to use it without Gulp or Grunt (or npm) as far as I know. CodePen doesn't support PostCSS stuff and I don't think CodeKit does either.

I have a small Sass/Gulp repo you can check out here: https://github.com/corysimmons/lost-sass-gulp

**Comment by corysimmons** [comment]
You could Tweet at Bryan and he might be able to help you with CodeKit instructions: https://twitter.com/bdkjones

I think he mentioned supporting this kind of workflow but I don't use CodeKit personally so I'm not familiar with how to do it.

**Comment by IbnSaeed** [comment]
I use Lost with NPM and Makefile, as i dont like to use Gulp, Grunt dependencies. It works great.
