### ISSUE TITLE
Flexbox layout is broken.

### ISSUE THREAD

**Issue by imrefazekas** [corysimmons/lost#124]
Hello,

The following test shows an interesting layout-bug:
https://dl.dropboxusercontent.com/u/5999/columnTest.zip

When you put "@lost flexbox flex;" into comment. the column-based layout works, with that line, it renders in the wrong way.
The line "lost-flex-container column" generates this:

    .columns {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-flex-flow: column nowrap;
        -ms-flex-flow: column nowrap;
        flex-flow: column nowrap;
    }

By removing the last 3 lines of the rules above, it renders fine.

**Comment by corysimmons** [comment]
I don't think this is broken. You need to be using `lost-flex-container: row` as specified here in the docs https://github.com/corysimmons/lost#lost-flex-container
