### ISSUE TITLE
Cycle fails when used with POST CSS Nested

### ISSUE THREAD

**Issue by fraincs** [corysimmons/lost#126]
here is a link to a project where it fails https://github.com/fraincs/postcss_starter, whenever I use lost-column inside a nested media query the cycle fails, while the width of the columns is ok. The issue can be seen in the index.html file of the linked Github and the code inside src/postcss/layout/main.css

**Comment by corysimmons** [comment]
@ai I've looked at this and can't seem to see what's going wrong. Lost seems to have a lot of issues with other PostCSS plugins. Is there any way I could convince you to review Lost's code and let me know if I'm doing something wrong to make it as modular as possible? =[

**Comment by ai** [comment]
@corysimmons right now I am preparing for CSSConf, so full reviewing will be very difficult.

@fraincs can you disable plugin by plugins too find a source of issue. Maybe it is a plugins conflict?

**Comment by corysimmons** [comment]
I think he narrowed it down to `postcss-nested` + `lost`.

https://github.com/fraincs/postcss_starter/blob/master/src/postcss/layout/main.css

**Comment by corysimmons** [comment]
Also, congrats on CSSConf! Spread the good word! (what are you talking about?)

**Comment by ai** [comment]
@corysimmons just a PostCSS overview

**Comment by corysimmons** [comment]
Please encourage people to write their libraries in it. It's been working great for me. =)

**Comment by fraincs** [comment]
Please do, PostCSS is awesome, it took me an evening to rewrite my setup from Stylus to PostCSS

**Comment by fraincs** [comment]
I found what happens here is the working code

@media all and (min-width: 700px) {

.lost-container div {
	background: #FF4136;
	width: calc(99.99% * 1/6 - 50px);
}

.lost-container div:nth-child(n) {
	float: left;
	margin-right: 60px;
	clear: none;
}

.lost-container div:last-child {
	margin-right: 0;
}

.lost-container div:nth-child(6n) {
	margin-right: 0;
}

.lost-container div:nth-child(6n + 1) {
	clear: left;
}

}

and the buggy code

@media all and (min-width: 700px) {

.lost-container div {
	background: #FF4136;
	width: calc(99.99% * 1/6 - 50px);
}

.lost-container div {
	float: left;
	margin-right: 60px;
	clear: none;
}

.lost-container div {
	margin-right: 0;
}

.lost-container div {
	margin-right: 0;
}

.lost-container div {
	clear: left;
}

}

every pseudo elements are removed I'll notice the postcss-nested developer

**Comment by corysimmons** [comment]
@fraincs Care to try this again with 6.4.0 and let me know if you're still having this problem?

**Comment by fraincs** [comment]
Looks good

**Comment by corysimmons** [comment]
Awesome! :)
