### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by CesarRotela** [corysimmons/lost#133]
Someone has the same message in Prepros?

![lost](https://cloud.githubusercontent.com/assets/1458649/7944229/741cb182-0937-11e5-9e11-11e6c5abd8c7.png)

**Comment by corysimmons** [comment]
Sorry, I'm no longer supporting the preprocessor versions of Lost. Check out the PostCSS version.

**Comment by CesarRotela** [comment]
What a pity! I think it will change to jeet.gs, all my projects are in SCSS

Thanks!

**Comment by corysimmons** [comment]
The PostCSS version of Lost works with SCSS as well. https://github.com/corysimmons/lost-sass-gulp
