### ISSUE TITLE
Why does it add `*zoom: 1`?

### ISSUE THREAD

**Issue by alebelcor** [corysimmons/lost#135]
Very interesting project.

My question is why is the output of, say, `lost-utility: clearfix` adding a `*zoom: 1` declaration in there? there are other places where it does that too.

`calc()` can only be used by IE9+ so it doesn't make sense to me that `lost` is outputting `*zoom` rules which are meant to address issues for < IE7.

Thanks!

**Comment by corysimmons** [comment]
With the calc polyfill I believe calc works in IE7. Regardless it's good practice to support older browsers if it doesn't hurt anything.
