### ISSUE TITLE
Just npm instead of gulp, grunt, brunch

### ISSUE THREAD

**Issue by dandv** [corysimmons/lost#139]
Lost seems really cool!

The installation instructions take about 1/3 of the README though. Have you seen [this post](http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/)? In the spirit of Lost's simplicity, npm might be a cleaner choice.

**Comment by corysimmons** [comment]
I've seen that post but haven't really tried it. Do you happen to have instructions for how to use Lost with just npm?

**Comment by kezzbracey** [comment]
I'm using Lost with just npm right now and it works beautifully.

I've made a CLI to go with my project, but it should also be doable following the instructions in that post as a starting point.

The first thing is to pull in PostCSS use it to process the raw CSS. Lost is added to the array of plugins that get passed into the postcss() function .

Then the basic code is something like this (untested stripped down version of my own file):

    var fs = require('fs-extra');

    // Post CSS and plugins
    var postcss = require('postcss');
    var lost = require('lost');

    exports.runPostCSS = function(){

      fs.readFile('raw.css', 'utf8', function(err, css ) {

        var lost_options = {"gutter": "30px", "flexbox": "no-flex", "cycle": "auto"};

        postcss([lost(lost_options)]).process(css).then(function (result) {

          result.warnings().forEach(function (warn) {
            console.warn(warn.toString());
          });

          fs.outputFile('processed.css', result.css, function (err) {
            if (err) throw err;
            console.log( 'css processed');          
          });

        });

      });

    }

Note, the options being passed don't work yet, but they will later. :-)

**Comment by igregson** [comment]
+1 for a full working example of how to wire-up Lost within the "NPM as a build tool" approach.

**Comment by dmitrykiselyov** [comment]
@dandv thanks for the link. 
@corysimmons I tried:

**package.json**
`npm install`
`npm run build:watch`
```json
{
  "dependencies": {
    "postcss-cli": "latest",
    "lost": "latest",	
    "watch": "latest"
  },
  "scripts": {
    "build:css": "postcss -u lost -o main-lost.css main.css",
    "build": "npm run build:css",
    "build:watch": "watch \"npm run build\""
  }
}
```
It works, but it has "ugly" delay between changes :sob:

**Comment by corysimmons** [comment]
@dmitrykiselyov How ugly of a delay? :\

**Comment by kezzbracey** [comment]
Could be worth trying [Chokidar](https://www.npmjs.com/package/chokidar) / [Chokidar CLI](https://github.com/kimmobrunfeldt/chokidar-cli) for potentially more efficient watching?

**Comment by corysimmons** [comment]
Anyone care to write instructions for this on https://github.com/corysimmons/lost/wiki/Installation ?

**Comment by kezzbracey** [comment]
IMO, it's not really down to Lost to cover how to use NPM as a build tool. It's outside the scope of the project, and trying to keep up with ensuring instructions like this work could be a pain.

However I can contribute docs / code snippet on how to use Lost as a PostCSS plugin, based on the assumption the end user is already writing their own NPM module / script.

I just did a quick check and this is what many of the other PostCSS plugins seem to do.

E.g. https://github.com/postcss/postcss-color-function#usage, https://github.com/ileri/postcss-bem#usage

**Comment by dandv** [comment]
> IMO, it's not really down to Lost to cover how to use NPM as a build tool.

Agree. My point was that [gulp & grunt are often not really necessary](http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/), but lots of devs use them just because they're popular. On the other hand, they already have npm, so npm instructions would cover all bases, and eliminate the need for writing instructions for other package managers.

**Comment by dmitrykiselyov** [comment]
@corysimmons 
> How ugly of a delay? :\

3 - 5 sec.
Brunch 90 ms.

**Comment by corysimmons** [comment]
Thanks @kezzbracey
