### ISSUE TITLE
The link to your example scss codepen uses center instead of container

### ISSUE THREAD

**Issue by mydudechris** [corysimmons/lost#14]
When following along, I kept running into 'center not found' errors. Upon inspection I found that your codepen has "@include center($pad: 30px, $mw: 800px);" while the .scss lib has replaced that with container.

**Comment by corysimmons** [comment]
Ah yes, I'm sorry. I changed it to `container` to be more in-line with what Bootstrap is doing. I think this will help people relate the two concepts easier. I'll update the CodePens now.

**Comment by corysimmons** [comment]
Note: Changes like this will be super infrequent. I think I just changed it because the lib is so new that I doubted many people were using it in production.

**Comment by mydudechris** [comment]
I really like what you've got going on with this project, I hope to use it in prod one day. Thanks!

**Comment by corysimmons** [comment]
@mydudechris Nice of you to say! I hope you do use it. I think you'll be really impressed and never go back to other grid systems.

**Comment by mydudechris** [comment]
Haha, me too!
