### ISSUE TITLE
Add line in README for stylus usage (w/ poststylus)

### ISSUE THREAD

**Issue by seaneking** [corysimmons/lost#140]
Feel free to say a resounding no to this one, but I put together a little Stylus -> PostCSS adapter that pipes PostCSS plugins to stylus builds (https://github.com/seaneking/poststylus) and thought it might handy to mention how you can use Lost as a Stylus plugin in the README, to ease the transition for all the Jeet converts out there.

That's pretty much why I built it, so I could easily use Lost (and a few other choice processors) with my existing stylus setup.

**Comment by corysimmons** [comment]
This is very neat. I think the installation section is getting a bit bloated though. I might break all the installation instructions out to the Wiki and include this.

**Comment by corysimmons** [comment]
Care to add instructions for this on https://github.com/corysimmons/lost/wiki/Installation ?

**Comment by seaneking** [comment]
Done. Figured you didn’t want to replicate all the taskrunner docs for stylus, so just pointed people to the poststylus docs for env-specific examples.

**Comment by corysimmons** [comment]
Cool, thanks!
