### ISSUE TITLE
Main file in bower.json

### ISSUE THREAD

**Issue by piermariacosina** [corysimmons/lost#144]
Would be nice to place a main file in the bower.json so the plugin it is easily usable with framework like brunch.io

**Comment by corysimmons** [comment]
There isn't a `bower.json` file anymore. Is this unusable with stuff like Brunch because of it?

**Comment by corysimmons** [comment]
@piermariacosina ping

**Comment by piermariacosina** [comment]
it is becoming a best practice in this way many task manager and framework
concat the file directly from bower_component files using the main
specification in their bower.json file

in this way you get something like vendor.js and vendor.css of all the main
files of the bower packages you install without need of dealing with
single files import
ᐧ

On Sat, Jul 18, 2015 at 8:29 PM, Cory Simmons <notifications@github.com>
wrote:

> @piermariacosina <https://github.com/piermariacosina> ping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/corysimmons/lost/issues/144#issuecomment-122576020>.
>



-- 

PIERMARIA COSINA
User Experience Designer | Product Developer

+39 392 4822 633 <http://assets.belafonte.co/signature.html#>
www.belafonte.co
<http://www.belafonte.co/?utm_source=signature&utm_medium=email&utm_campaign=signature>
