### ISSUE TITLE
Turn LostGrid compatible with linters

### ISSUE THREAD

**Issue by brunowego** [corysimmons/lost#146]
Have any way to turn LostGrid compatible with linters like [SCSS Lint](https://github.com/brigade/scss-lint)? Thanks.

**Comment by corysimmons** [comment]
I'm not sure. It might be possible to do with Gulp but I haven't tried it. What problems are you having?

**Comment by brunowego** [comment]
No Problem. It was only a hint. :+1: Thanks @corysimmons.

**Comment by corysimmons** [comment]
Ah, sorry, the compiled CSS should be SCSS Lint (any CSS linter) compatible since it's just CSS.
