### ISSUE TITLE
Can't insert params for grid in LESS file

### ISSUE THREAD

**Issue by p-ivannikov** [corysimmons/lost#149]
When i'm trying to add param for lost-grid ```@lost gutter 10px``` in less file i've got error message when gulp-less processed it. Can you say me how i can send parameters in lost-grid?

**Comment by corysimmons** [comment]
Sounds like an error with LESS. LESS should just ignore at-rules like that. Would you mind opening an issue with them?

Stylus had the same problem but I opened an issue with them and they fixed it within a few hours.

**Comment by corysimmons** [comment]
Thanks for opening an issue. Definitely a problem on LESS' part and it looks like it will be in the pipeline eventually: https://github.com/less/less.js/issues/2639
