### ISSUE TITLE
Align mixin in Safari not aligning vertically

### ISSUE THREAD

**Issue by mydudechris** [corysimmons/lost#15]
Looks like Safari 8+ is expecting the following:

display:-webkit-flex;
-webkit-align-items: center;

**Comment by corysimmons** [comment]
Are you using a tool like Autoprefixer to do your prefixing?

**Comment by mydudechris** [comment]
Nope, just calling the mixin.
```

section {
  @include container($pad: 30px);
  @include align;
  width: 70%;
  height: 100vh;
}
```

**Comment by corysimmons** [comment]
Yes you need to use a tool like Autoprefixer to do this.

FWIW, if I could give any dev one piece of advice or one tool to use, it would be Autoprefixer. It's by far the most helpful tool I've ever used in all of my development.

**Comment by corysimmons** [comment]
It will automatically do all the flexbox prefixing in the correct order and with the correct syntaxes for all the browsers that support it. https://css-tricks.com/autoprefixer/
