### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by HarrisRobin** [corysimmons/lost#154]
Hi,

This looks awesome! However.. I don't know how to integrate it into my project which uses webpack. Is there a way to use this with webpack without having to go through gulp/grunt?

**Comment by corysimmons** [comment]
To be honest I'm not sure. I've never used WebPack.

Does WebPack let you use npm packages?

Seems like PostCSS has a solution to this: https://github.com/postcss/postcss-loader

Let me know if you get it working. I'd love to add this to the integration wiki.

**Comment by HarrisRobin** [comment]
My question was kind of silly. It just works. Using postcss-loader, this is what I did after using npm to install lost:

```
postcss: [
    require('postcss-nested')(),
    require('cssnext')(),
    require('autoprefixer-core')(AUTOPREFIXER_BROWSERS),
    require('lost')
  ]
```


And that's it. Webpack handles the rest and lost-grid works.

This should just be a couple of lines for your wiki, let me know if you need a PR.

Cheers,

**Comment by corysimmons** [comment]
I'd love a working example in the Wiki. Can you edit it or do you need special permissions? https://github.com/corysimmons/lost/wiki/Installation

**Comment by HarrisRobin** [comment]
I'll send you a PR either tonight or tomorrow!

Cheers

**Comment by corysimmons** [comment]
Thanks Harris!
