### ISSUE TITLE
undefinedn

### ISSUE THREAD

**Issue by clemsontiger** [corysimmons/lost#159]
SCSS code I'm using:

```
@for $i from 1 through $grid-columns {	

		.col-#{$i*5} {    //for more col size options for tables
			lost-column: $i / $grid-columns;
		}
				
	}
```
where $grid-columns = 20

which is compiling to:
...  (only showing one section for brevity)
```
.col-10 {
    width: calc(99.99% * 0.1 - (30px - 30px * 0.1));
  }

  .col-10:nth-child(n){
    float: left;
    margin-right: 30px;
    clear: none;
  }

  .col-10:last-child{
    margin-right: 0;
  }

  .col-10:nth-child(undefinedn){
    margin-right: 0;
  }

  .col-10:nth-child(undefinedn + 1){
    clear: left;
  }
```
...
what's with the "undefinedn" ? 

any help is greatly appreciated.

**Comment by clemsontiger** [comment]
sigh, I think it's because I'm compiling the scss first and it's convertin $i/$grid-columns to a decimal... so like it gives .col-10 { lost-column: 0.1; } going to see about getting it to leave it as a fraction

**Comment by corysimmons** [comment]
What happens when you compile Lost first and then Sass?

**Comment by clemsontiger** [comment]
same result if I compile Lost first then sass


![2015-08-28_10h35_58](https://cloud.githubusercontent.com/assets/6810728/9548855/d2a85814-4d70-11e5-8b50-e44ca2cfc35c.png)

**Comment by corysimmons** [comment]
This is a problem, but moreover, what you're trying to do won't work like I think you're expecting it to. I don't think there's a way to generate functional classes like that with Lost _yet_.

I'll look into this though and get back to you in a few days.

**Comment by clemsontiger** [comment]
ah, figured it out. had to do this:

```
.col-#{$i*5} {    //for more col size options for tables
			lost-column: unquote($i + '/' + $grid-columns);
		}
```

which now gives:

```

  .col-10 {
    width: calc(99.99% * 2/20 - (30px - 30px * 2/20));
  }

  .col-10:nth-child(n){
    float: left;
    margin-right: 30px;
    clear: none;
  }

  .col-10:last-child{
    margin-right: 0;
  }

  .col-10:nth-child(20n){
    margin-right: 0;
  }

  .col-10:nth-child(20n + 1){
    clear: left;
  }

```

sorry, not a lost grid thing but instead a lack of sass knowledge on my part.

**Comment by corysimmons** [comment]
Keep me posted on whether you get functional classes out of this. I'm betting all the nth-child stuff will mess it up.

I really need to add a function in there that generates classes like this.
