### ISSUE TITLE
Full page width?

### ISSUE THREAD

**Issue by aolko** [corysimmons/lost#16]
How to achieve full page width? (100%)
Currently pages look like this (default settings)(Notice those blue margins)
![hey](http://i.imgur.com/r4OpflA.png)

**Comment by corysimmons** [comment]
Let me know if this helps: http://codepen.io/corysimmons/pen/RNverG

**Comment by aolko** [comment]
chrome still shows width:1000px in your codepen (section element)

**Comment by corysimmons** [comment]
Oh gosh you're right!

I updated the CodePen to work.

This isn't very intuitive though is it?

**Comment by corysimmons** [comment]
Thoughts on some better syntax for it?

**Comment by corysimmons** [comment]
It's defined [here](https://github.com/corysimmons/lost/blob/master/stylus/lost.styl#L103) if you want to see the source code.

**Comment by aolko** [comment]
i'm using scss one :)
and i don't have a single container, 4 rows instead
![rows](http://i.imgur.com/9pzHuaM.png)

**Comment by corysimmons** [comment]
Hm, I see. Let me look at arnaudleray/pocketgrid and think about this for a bit...

**Comment by corysimmons** [comment]
Oh nevermind, this works perfect: http://codepen.io/corysimmons/pen/RNverG

Sorry, I was overcomplicating the situation (haven't had a chance to use my own grid system a ton yet hehe).
