### ISSUE TITLE
lost-column calc output

### ISSUE THREAD

**Issue by gabormeszoly** [corysimmons/lost#162]
Why 99.99% instead of 100%?
```
div {
  width: calc(99.99% * 1/3 - (20px - 20px * 1/3));
}
```
ps: Lost is Awesome :)

**Comment by dmitrykiselyov** [comment]
@gabormeszoly because IE subpixel https://github.com/corysimmons/lost/issues/42

**Comment by gabormeszoly** [comment]
@dmitrykiselyov thanks mate – terrible

**Comment by corysimmons** [comment]
Thanks @dmitrykiselyov 

Meant to answer this one but got busy and forgot.
