### ISSUE TITLE
Use from javascript.

### ISSUE THREAD

**Issue by serapath** [corysimmons/lost#167]
Hey :-)
I'm currently trying out [jss](https://github.com/jsstyles/jss) and i'm writing my components using `js`, `hyperscript` (instead of JSX) and `jss` (instead of css), so they look like:

```jss
// STACK
var h       = require('virtual-hyperscript-hook')(require('virtual-dom/h'))
var jss     = require('jss')
var css2jss = require('jss-cli/lib/cssToJss')

var SHEET
function initSheet (css) {
  SHEET = jss.create().createStyleSheet(css2jss(css),{ named: true, link: true }).attach()
}
function s (name, modifier) {
  modifier = modifier ? '  ' + sheet.classes[modifier] : ''
  name     = SHEET.classes[name]
  return name + modifier
}

module.exports = ContentComponent

function ContentComponent (state) {
  // STYLING
  if (!SHEET) {
    initSheet(`
    .content {
      background-color  : seagreen;
      display           : flex;
      align-items       : center;
      justify-content   : space-around;
      height            : 300px;
    }
    .box {
      text-align        : center;
      background-color  : yellow;
      padding           : 20px;
      font-size         : 20px;
      height            : 200px;
      width             : 300px;
    }
    `)
  }
  // RENDER TEMPLATE
  return function Content (state) {
    return h('div', { className: s('.content') }, [
      h('div', { className: s('.box') }, [
        h('div', 'Learning Experience'),
        h('div', state.learningexperience)
      ]),
      h('div', { className: s('.box') }, [
        h('div', 'Female Leadership'),
        h('div', state.femaleleadership)
      ]),
      h('div', { className: s('.box') }, [
        h('div', 'Book'),
        h('div', state.book)
      ]),
    ])
  }
}
```

As you can see, instead of having 3 files `component.css`, `component.html`, `component.js`, it's all readuced to one `component.js` file, which uses `virtual-hyperscript` to create the markup and `jss` to create the styling. The `css` is authored inside of an `es6 template string`.

I have little to no experience with responsive grid systems, but I used `jeet` in the past.
**Is it possible to `require('lost-grid')` and somehow use it in a way that would be easily combined with `jss`?

If not - then how does `lost` work and what would in theory be needed to make it work with `jss`?

**Comment by corysimmons** [comment]
I'm still not familiar with JSS enough (or get enough requests for it really) to do special work to make Lost compatible with it.

I'd love it if you could test this out and update the Wiki with instructions on how to use with JSS though. I imagine a lot of people are using PostCSS packages with JSS.

Closing for now.
