### ISSUE TITLE
Node#removeSelf is deprecated. Use Node#remove.

### ISSUE THREAD

**Issue by peterramsing** [corysimmons/lost#168]
We're getting the error `Node#removeSelf is deprecated. Use Node#remove.` while compiling lost using the npm packages for lost and postcss

gulp-postcss: 6.0.0
lost: 6.6.0

Was able to quiet the error with a find and replace in `lost.js`.

I haven't done any extensive testing to ensure it's still working but seems like a simple fix. Is cleaning up the deprecated code from Postcss 5 in the roadmap? Should I create a pull request?

**Comment by corysimmons** [comment]
I'd love a pull request! We have testing. You guys rock! :dancer:

**Comment by corysimmons** [comment]
Wubba lubba dub dub!
