### ISSUE TITLE
Horizontal Scroll on Chrome Mobile

### ISSUE THREAD

**Issue by Chudz** [corysimmons/lost#17]
I am getting horizontal scrolling on Chrome mobile. Here is my styl file:
```
@import 'lost'
html
     overflow-x hidden
section
	row()
	article
		cycle(3)
		column(1/3)
```
Here is my html file:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Template</title>
    <link href="css/styles.css" rel="stylesheet">
  </head>
  <body>
    <section>
      <article>
        1
      </article>
      <article>
        2
      </article>
      <article>
        3
      </article>
      <article>
        4
      </article>
      <article>
        5
      </article>
      <article>
        6
      </article>
    </section>
  </body>
</html>
```

Is this a bug or am I missing somthing?

Thanks

**Comment by corysimmons** [comment]
Try `body { overflow-x: hidden; }` and let me know if that fixes it.

**Comment by corysimmons** [comment]
Your code would work on desktop.

**Comment by Chudz** [comment]
Thanks adding it to body worked :+1:

**Comment by corysimmons** [comment]
Hm. It's interesting that it needs to be on both. Are you sure?

**Comment by Chudz** [comment]
Works fine on desktop with just html overflow but on my HTC One with Chrome I have to add it to both html and body tags for some reason.

**Comment by corysimmons** [comment]
What about if you just use `body`?

**Comment by Chudz** [comment]
Yeah tried it :) it comes back with the small horizontal scroll. Tried with just html on its own and body on its own.

**Comment by corysimmons** [comment]
Hm. Super weird.

**Comment by corysimmons** [comment]
Fixed this in https://github.com/corysimmons/boy

**Comment by Chudz** [comment]
Ah thanks I will check that out. I was using my own quick reset with:
	*
		margin 0
		padding 0
I guess it this was the issue?

**Comment by corysimmons** [comment]
The issue is that `row` creates negative margins on each side (so margins on items will touch the edges of `container`).

If you don't have a container, those negative margins actually go off the page.

This is expected behavior and easily fixed with `overflow-x` hidden. Thanks for pointing out it didn't work on mobile.
