### ISSUE TITLE
Calc 99.99% vs 99.999999%

### ISSUE THREAD

**Issue by abstracthat** [corysimmons/lost#174]
Just curious. I know the almost 100% value is to handle cross-browser sub-pixel rounding inconsistencies, but I'm not sure why you use 99.99% when there is no gutter and 99.999999% when there is. Why not use one or the other for both?

**Comment by corysimmons** [comment]
These numbers are the result of having various versions of all the browsers open and trying out variations of 99.xxxxxxxxxxxxxxxxx%. Some browsers would kick blocks down into the next row when these numbers were set to anything else. Are they causing you any problems?

**Comment by abstracthat** [comment]
Nope. Just wondering. Thanks!
