### ISSUE TITLE
Different @lost gutter values

### ISSUE THREAD

**Issue by neonick** [corysimmons/lost#176]
Can I use on the page several different ```@lost gutter```? (for example 30px and 10px)

I have several grids with different gutter on the same page, but I could not figure out whether it is possible use for this purpose Lost Grid.

**Comment by peterramsing** [comment]
@neonick You can specify the gutter right in `lost-column`. [Here's more](https://github.com/corysimmons/lost#lost-column)

**Comment by neonick** [comment]
I am just inattentive, I'm sorry to trouble you. Thank you.
