### ISSUE TITLE
If anyone is interested

### ISSUE THREAD

**Issue by findborg** [corysimmons/lost#18]
First of all,  I love this calc based grid.  Good job Cory.
Second,  If anyone is interested I have built a fully responsive 12 col grid system with 4 MQ breaks using Corys' code.  I could share what I have done and maybe get some help to perfect it...  My initial tests have shown that it works great.

**Comment by corysimmons** [comment]
Sure, post the project and I'll take a look at it.

**Comment by findborg** [comment]
Do you want something online or here on Github?

**Comment by corysimmons** [comment]
Always Github =)

**Comment by findborg** [comment]
Ok don't laugh.  I did not have much time to throw this together.
But here is example of the 12 col grid.   I have your scss files in the less folder.  
https://github.com/Findborg-Coop/borgcss
I do not have a demo online yet.

**Comment by corysimmons** [comment]
Not sure what I'm looking for exactly. I don't really see where Lost is being used either.

You have a pretty big/unorganized project here. Have you considered scaling it down to have various repos for various purposes? Like have your typography in one repo, grids in another, etc. Then you could bring them all into an all-encompassing repo as [Git submodules](http://git-scm.com/book/en/v2/Git-Tools-Submodules)?

Closing this as it isn't really an issue with Lost. We can keep talking here or on your repo if you prefer?

**Comment by findborg** [comment]
https://github.com/Findborg-Coop/borgcss/blob/master/less/style.scss

It was a quick upload.  As I wanted you to see...

**Comment by corysimmons** [comment]
Very cool. If you want to clean up the repo and turn it into just the CSS grid system I'll link to it.

**Comment by corysimmons** [comment]
Although, what's the difference between this and Bootstrap's 12 column grid?

**Comment by corysimmons** [comment]
@findborg I introduced some code for making CSS grid systems even easier/cleaner. Check out some example SCSS here: https://github.com/corysimmons/lost/issues/19
