### ISSUE TITLE
NPM Lost Grid using deprecated functions

### ISSUE THREAD

**Issue by elimc** [corysimmons/lost#182]
I'm using Lost Grid in my WordPress theme [gulpfile.js](https://github.com/elimc/jumpstart/blob/master/gulpfile.js). 

This is the error I get when I run Lost Grid with Gulp:

```javascript
Node#semicolon is deprecated. Use Node#raws.semicolon
Node#after is deprecated. Use Node#raws.after
Container#eachComment is deprecated. Use Container#walkComments instead.
Node#before is deprecated. Use Node#raws.before
Node#removeSelf is deprecated. Use Node#remove.
Node#before is deprecated. Use Node#raws.before
Node#removeSelf is deprecated. Use Node#remove.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#between is deprecated. Use Node#raws.between
Node#_important was deprecated. Use Node#raws.important
Container#eachRule is deprecated. Use Container#walkRules instead.
Node#semicolon is deprecated. Use Node#raws.semicolon
Node#after is deprecated. Use Node#raws.after
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
AtRule#afterName was deprecated. Use AtRule#raws.afterName
```

My build info:
Node 4.2.0
Gulp CLI version 0.4.0
Gulp Local version 4.0.0-alpha.1
Lost 6.6.2

Lost Grid still works, but the build time is like 200ms when the CLI has to display an error. When errors are silenced, my build time is like 23ms. Thus, it would be nice to get the functions updated, and it would probably reduce the confusion of new users.

**Comment by peterramsing** [comment]
What version of gulp-postcss?

**Comment by elimc** [comment]
You know what? There appear to be two versions of postcss. I was using gulp-postcss 6.0.1, when I got the error. Do you just use the postcss npm module?

**Comment by peterramsing** [comment]
We're on:
`lost: 6.6.2`
`gulp-postcss: 6.0.1`

It looks like those warnings might not be lost. I updated the `removeSelf` in lost in #169 .

Have you confirmed it's not the other plugins?

**Comment by elimc** [comment]
That very well could be. I ran ```npm ls postcss``` in the CLI. I received the following:

```javascript
├─┬ autoprefixer@6.0.3
│ └── postcss@5.0.10
├─┬ css-mqpacker@4.0.0
│ └── postcss@5.0.10
├─┬ csswring@3.0.7
│ └── postcss@4.1.16
├─┬ gulp-postcss@6.0.1
│ └── postcss@5.0.10
├─┬ lost@6.6.2
│ └── postcss@5.0.10
└─┬ precss@1.2.3
  └── postcss@5.0.10
```

I'm not sure what the package underneath the main package means?

**Comment by peterramsing** [comment]
Have you tried one of those plugins at a time to determine what one might be causing it?

**Comment by elimc** [comment]
You are correct, Sir. It seems to be an issue with csswring (https://github.com/hail2u/node-csswring). I'll follow up with them or find a different way to compress my CSS.

**Comment by peterramsing** [comment]
The update is usually pretty easy. Good luck!
