### ISSUE TITLE
Consider SassDoc comments

### ISSUE THREAD

**Issue by HugoGiraudel** [corysimmons/lost#2]

**Comment by corysimmons** [comment]
:+1:

**Comment by corysimmons** [comment]
Reading the docs now. Will actually try to get this done today. Do you know of any projects currently using SassDoc that I can look into?

**Comment by HugoGiraudel** [comment]
http://sassdoc.com/gallery/

And plenty more missing.

**Comment by corysimmons** [comment]
@HugoGiraudel Hey I'm trying to implement these. Do you care to review my attempt and let me know if I'm doing anything wrong or if something could be better/more thorough? https://github.com/corysimmons/lost/blob/cs/sass-docs/lost.scss

**Comment by corysimmons** [comment]
Eh I tested it out with the `sassdoc` npm tool and it seems to generate appropriate docs. Cool tool. Thanks @HugoGiraudel 

Fixed https://github.com/corysimmons/lost/commit/3df00e350ade768ec6781ad7a4e62a14e04df016
