### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by microcipcip** [corysimmons/lost#20]
What are the basic requirements to make this grid system work on IE8? Would it be enough to add Respond, html5shiv, and a [calc-polyfill](https://github.com/closingtag/calc-polyfill)? I know that the align() mixin won't work, but that's ok, I just wonder if the main grid can be used with the simple addition of calc-polyfill? I have used selectivizr in the past but usually doesn't work very well when you combine it with respond, expecially in a complex layout.

**Comment by corysimmons** [comment]
I haven't done a lot of testing of the calc version in IE8 but I'd imagine using a nice boilerplate like https://github.com/corysimmons/boy in combination with calc-polyfill would probably work except for media queries (last I checked calc-polyfill didn't really work with media queries).

**Comment by microcipcip** [comment]
Ok, I'll try if it works then. Thanks for the reply, I'll close this issue for now.

**Comment by corysimmons** [comment]
I just tested it. It doesn't work because the calc polyfill doesn't work with multiplication or division of percentages: https://github.com/closingtag/calc-polyfill/issues/8

**Comment by corysimmons** [comment]
Yeah, the best support I can get is using the `$old` variable and Boy for IE8 support. IE7 boxsizing polyfill doesn't even work anymore.

**Comment by corysimmons** [comment]
I fixed the box-sizing polyfill in Boy so IE7 works again.

Apparently they merged a PR that broke percentage widths... https://github.com/Schepp/box-sizing-polyfill/issues/49
