### ISSUE TITLE
Sass 3.2

### ISSUE THREAD

**Issue by HugoGiraudel** [corysimmons/lost#3]
Do you still need to support Sass 3.2?

**Comment by corysimmons** [comment]
Not sure. How unpopular is it nowadays?

**Comment by HugoGiraudel** [comment]
Not sure we have stats about this, but I think it is safe to say it's getting old.

**Comment by corysimmons** [comment]
Want to PR this as well after you rebase the other PR?

**Comment by corysimmons** [comment]
Will merge
