### ISSUE TITLE
Consider converting to float: left; margin-right/bottom

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/lost#30]
This would get rid of the extra markup but break masonry.

Users would have to set `cycle` for every batch of elements.

Worth?

**Comment by corysimmons** [comment]
If we go this route, re-add `center` mixin as it was kinda handy.

**Comment by corysimmons** [comment]
Maybe add a setting for this? `$masonry-markup` or something.

**Comment by stolinski** [comment]
I don't mind the negative margin stuff myself, but maybe like you mentioned a setting to change the type. I think leaving the current style as the default would be best as long as that overflow-x:hidden is added by default.

**Comment by corysimmons** [comment]
After using it in real projects for a while now, then going back to use Jeet a few times, I really feel like the markup is a huge turnoff for me. I think I'll add a global setting as well as mixin params (so if you want terse markup 99% of the time and just need masonry for one or two areas...).

I also think I'm going to make the default terse. Why do you suggest making default the margins on both sides? Just because that's what it is already?

**Comment by stolinski** [comment]
That was pretty much why. Thinking about it more though, I would be more likely to use it with terse markup especially coming from using Susy & Jeet primarily.

**Comment by stolinski** [comment]
Also, the terse markup makes it way easier to see what's going on. It's also easier for people new to the grid or style of grid to quickly get up to speed.

**Comment by corysimmons** [comment]
Yeah exactly. I'll try to get these changes in today. Maybe instead of a default global setting I'll just have it like `box($masonry: true)` and `block($masonry: true)`.

**Comment by corysimmons** [comment]
I'm churning out some pretty sick `calc()` for this but I'm pretty sure we're going to *always* have to pass a `$cycle` param which kinda makes me sad.

**Comment by stolinski** [comment]
Hm, agreed. It would be hard for `$cycle` to have a useful default value as well because it's almost always going to be different.

**Comment by corysimmons** [comment]
I'm actually trying to figure out how to make the default the denominator right now.

This way you could simply say `block(1/4)` and every 4th element would automatically cycle, but I'm also going to offer the `$cycle` param in case people want control over it.

**Comment by corysimmons** [comment]
It's turning out rather well if I do say so myself. Jeet markup without Jeet's need to declare cycle, and without Jeet's need for additional parent ratios if you nest.

If I can nail this, it will be really unique to preprocessor grid systems since they all require you to pass additional contexts as you nest in some form or fashion.

**Comment by corysimmons** [comment]
![](http://i.imgur.com/wIul36G.png)

Boomshakalaka. No `overflow-x: hidden` or anything.

**Comment by stolinski** [comment]
Nice! That's going to be awesome to use.

**Comment by corysimmons** [comment]
Works perfect with the vertical grid stuff too. So stoked. :)

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/a5b81584ea620817cf7268a2601af423fff867c5

**Comment by corysimmons** [comment]
There. It's pretty totally badass now. Read the README carefully and enjoy! =)
