### ISSUE TITLE
Zero gutter break block(column) layout

### ISSUE THREAD

**Issue by hotovec** [corysimmons/lost#31]
When you set block(... $gut:0) it breaks columns
http://codepen.io/mhotovec/pen/dPLpar

**Comment by corysimmons** [comment]
Ah, thanks for pointing this out. Will fix today.

**Comment by corysimmons** [comment]
@hotovec Fixed https://github.com/corysimmons/lost/commit/83b01135df24f3d036828bab74c3a96123c4be32

Thank you for pointing these out!
