### ISSUE TITLE
@align mixin wrong direction parameter ($dir vs $direction)

### ISSUE THREAD

**Issue by hotovec** [corysimmons/lost#32]

**Comment by corysimmons** [comment]
I changed this to `$dir` to be more inline with the other mixins. Is this what you're talking about?

**Comment by hotovec** [comment]
yup, but you have $direction in rest of align() and sass error is throwing.

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/83b01135df24f3d036828bab74c3a96123c4be32

Sorry I didn't address this sooner - was asleep. Thanks for looking out and taking the time to report.
