### ISSUE TITLE
Consider changing $cycle name

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/lost#36]
`$cycle` doesn't just control things looping to the next row anymore. It's sometimes part of the math involved.

Maybe something esoteric like Neat's `$omega`, or something descriptive like `$ipr` ("items per row").

Open to ideas on this, but I'd really like to move away from `$cycle`.

**Comment by dmitrykiselyov** [comment]
I like  `$items-per-row` or just `$items` :smile:

**Comment by corysimmons** [comment]
I think `$items-per-row` is a bit too long to have people write out all the time and I thought about `$items` but want it to be a bit more descriptive.

I think I like `$ipr`.

**Comment by huyhong** [comment]
I think most grid folks refer to content blocks as `modules`, so `$mpr` ("modules per row") would fit more in the descriptive manner.

For generic CSS lingo, something akin to `$clear` or `$repeat` makes more sense.

**Comment by corysimmons** [comment]
@huyhong It's so tied to the sizing of stuff I don't know if `$clear` or `$repeat` makes sense (and is why I'm trying to move away from `$cycle`), but `$mpr` could work.

**Comment by corysimmons** [comment]
Hell, now that I'm toying with it, `$items` feels pretty good actually.

**Comment by dmitrykiselyov** [comment]
`$items-per-row` is to long `$ipr` is to abbreviation `$items` is :+1:

**Comment by corysimmons** [comment]
I think I'm gonna go with `$items`, but right now I'm struggling to even get the grid working in IE (no surprise who the culprit is). I'm working hard to figure out a solution.

**Comment by dmitrykiselyov** [comment]
what IE version?

**Comment by corysimmons** [comment]
All of them. Check out the demo.

I didn't notice it because it's a subpixel rounding error, so when I was testing I must have had my browser width set to the perfect number of pixels because it didn't appear until I pushed 3.0.0, then I got a report of it being broken. :'(

**Comment by corysimmons** [comment]
No worries. Fixed locally.

**Comment by corysimmons** [comment]
Ended up staying with `$cycle` as the grid's sizing functions are no longer dependent on it and the param actually is explicitly designed to be used to cycle elements to the next row.

Fixed https://github.com/corysimmons/lost/commit/fa81e90a0bd9786c2057456ad0f7c12f527e5596
