### ISSUE TITLE
IE subpixel rounding breaks everything

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/lost#42]
Seriously, I hate this browser more and more every day.

**Comment by corysimmons** [comment]
Try isolation technique. If that doesn't work. Kill self.

**Comment by corysimmons** [comment]
Seems like it works. Need to do some more tests.

**Comment by dmitrykiselyov** [comment]
Its ok, grid just dancing :smile: IE patry :boom:
`calc(100% * 1/3 - 0.01px - (30px - 30px /3))` works this way - 0.01px

**Comment by corysimmons** [comment]
Gah! Why couldn't you have said that 3 hours earlier! I've been converting the whole thing over to the [isolation method](https://css-tricks.com/build-web-layouts-easily-susy/)!

**Comment by dmitrykiselyov** [comment]
or `calc(99.99% * 1/3 - (30px - 30px /3))`

**Comment by corysimmons** [comment]
Awesome! Thanks @dmitrykiselyov :+1: 

Fixed https://github.com/corysimmons/lost/commit/2cb9c9e762c0dea7c0c7a9f4b2618b71fbc3320e

**Comment by dmitrykiselyov** [comment]
no no no 99.99% :smile: 
better -0.01px

**Comment by corysimmons** [comment]
Why `99.99%` or `-0.01px`?

`99.999%` seems to work fine and has better precision?

**Comment by dmitrykiselyov** [comment]
with a large width, the difference between 99.99 and 0.01can be 1px and >

**Comment by corysimmons** [comment]
How large? I'm on a 2880 x 1800 retina and it works fine.

**Comment by corysimmons** [comment]
I'll take your word for it.

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/44234ec7de1d142d85d0eb8ea47bbd3ed9144b74

**Comment by corysimmons** [comment]
I may end up going with isolation anyway (depending on if I can get the `move()` formula working easier with it or not), but this is a really great hotfix. Thanks again :+1:

**Comment by dmitrykiselyov** [comment]
I tested again, and there is no difference between 99.99% and 0.01 :smile:
