### ISSUE TITLE
Namespacing!

### ISSUE THREAD

**Issue by davidkpiano** [corysimmons/lost#50]
Great project, Cory, but I strongly, strongly suggest that you namespace your mixins (and functions, if applicable). Names such as `edit`, `center`, `block`, etc. are very general and there is a high likelihood that this could cause naming collisions with mixins/functions in other projects.

Perhaps something like `lost-block`, `lost-center`, etc.?

**Comment by corysimmons** [comment]
I've definitely thought about it, but no one else really does this. Susy, Neat, Jeet, etc. and I never have collisions.

If I did implement namespacing it would be `l-` for terseness.

Not adding this right now, but I will leave this issue open in case someone actually runs into a collision or a lot more people think this is a good trade.

**Comment by corysimmons** [comment]
Actually I'm gonna go ahead and close this as I don't think I want to namespace at this time.

I'll definitely keep it in mind though and the first time someone actually runs into this problem and reports an issue I'll revisit my thoughts on it.
