### ISSUE TITLE
$rtl variable is right-to-left when false

### ISSUE THREAD

**Issue by teddybradford** [corysimmons/lost#52]
Using the SCSS version, I made a test using the sample code provided in the README:

```
<section>
  <figure>1</figure>
  <figure>2</figure>
  <figure>3</figure>
  <figure>4</figure>
</section>

section {
  @include cf;
}

figure {
  @include block('1/2');
}
```

However, it seems that right-to-left mode is the default. The list of numbers displays as: "2, 1, 4, 3" by default. When $rtl is set to true, it displays the way I would expect it to if $rtl was false: "1, 2, 3, 4". Either I've overlooked something or there is a faulty $rtl conditional in the code.

**Comment by corysimmons** [comment]
You might be right. I'll check this out and push a fix in the next hour or so. Thanks for pointing this out!

**Comment by teddybradford** [comment]
Thanks!

I'm not sure if it's related, but it also seems that this logic:
```
Every element gets a float: left and margin-right: $gutter applied to them except the last one in the row.
```
is also reversed; the $gutter seems to be applied to only the last row rather than all except the last row.

**Comment by corysimmons** [comment]
Which version of Lost are you using? I'm testing 4.1.1 (the latest) on CodePen here and it seems to work fine: http://codepen.io/corysimmons/pen/wBbzJb

**Comment by teddybradford** [comment]
Hmm, I'm also using 4.1.1. I'm taking another look through my code to see if there's an issue elsewhere.

**Comment by corysimmons** [comment]
Super weird. :x:

**Comment by corysimmons** [comment]
Please update me when you find out what it is so I can make sure Lost isn't broken anywhere. =)

**Comment by teddybradford** [comment]
It seems the issue may be caused by a difference in compilation of the Lost SCSS by gulp-sass (I'm using the latest stable v1.3.3) compared to CodePen's compiler. I forked your CodePen and pasted in the gulp-sass compiled CSS so you can see the result I'm getting: http://codepen.io/teddybradford/pen/Ggajmw

**Comment by teddybradford** [comment]
Found the problem: gulp-sass is having trouble with the nth-child parameters.

```
figure:nth-child(n)
...
figure:nth-child(n+1)
```

vs.

```
figure:nth-child(2n)
...
figure:nth-child(2n + 1)
```

**Comment by corysimmons** [comment]
@teddybradford Thanks for your help! I've filed a bug with gulp sass. Hopefully they'll fix it soon.

**Comment by corysimmons** [comment]
In the meantime, might I suggest you try out the absolutely amazing and beautiful glory that is Stylus?

**Comment by teddybradford** [comment]
gulp-sass is just a wrapper for libsass, so my guess is that the bug is probably in libsass. Maybe CodePen uses the Ruby version of Sass for it's compilation.

I'll definitely play around with Lost using Stylus. I was just trying to see if I could merge this grid system into an existing SCSS code base I have.

**Comment by corysimmons** [comment]
I'll wait until the Gulp Sass people reply on the bug and then file it at LibSass if that's the case.

SassMeister is about to add Lost to their site so I'll be able to test it there (I'm not a Sass guy so I don't know how to use LibSass and all that confusing jazz).

**Comment by corysimmons** [comment]
@teddybradford This is fixed in LibSass 3.2.0 which should be released sooner than later. In the meantime enjoy Stylus or Sass w/o LibSass.

**Comment by teddybradford** [comment]
Awesome. Glad we figured it out!

**Comment by corysimmons** [comment]
Again, thanks for pointing this out and I hope you enjoy the rest of your experience with Lost. =)
