### ISSUE TITLE
Setup Documentation

### ISSUE THREAD

**Issue by mooror** [corysimmons/lost#53]
Hey Cory, first off i just want to say that I am extremely excited about this grid and can't wait to try it out. I think it will really add to the projects that  I am currently working on. Now,excitement aside I cannot seem to get your grid working and would really love if you could create a step by step guide on how to setup the lost grid. 

Thanks so much, Mooror

**Comment by corysimmons** [comment]
Hey man! Glad you're excited. Can you tell me what preprocessor you're using and I can help guide you through it?

**Comment by mooror** [comment]
Thanks for the quick reply. Im using scss (sass). I also have ruby,node,npm,grunt,and compass. I use those for my normal work setup.

**Comment by corysimmons** [comment]
- `mkdir ~/my-project`
- `cd ~/my-project`
- `bower i lost-grid`

Then create your project (index.html, style.scss) and `@import '../bower_components/.../scss/lost.scss';` at the top of your `style.scss`.

Then test it out with `@include edit;` (everything should turn light blue) and make sure to `sass -w style.scss:style.css`.

Let me know if that helps. If not, I'll send you a .zip with a little sample project.

**Comment by corysimmons** [comment]
You're right though, I need to add some Install docs.

**Comment by mooror** [comment]
Hey cory thanks agian for all this help. I did what you said and installed the lost grid through bower and the page turned blue just as you said it would, however when I place this code in my scss
@import '../bower_components/lost-grid/scss/lost.scss';
@include edit;


section {
  @include center(980px);
}

figure {
  @include block('1/2');
}
I get this result: http://i1327.photobucket.com/albums/u675/mooror/lostGrid_zpsayoxuyey.png

**Comment by mooror** [comment]
My html is as follows:
<!DOCTYPE html>
<html >
  <head> 
    <link rel="stylesheet" href="css/style.css">
    
  </head>
  <body>
  
     <section>
      <figure>Sidebar</figure>
      <figure>Content</figure>
    </section>
    
  </body>
</html>

**Comment by corysimmons** [comment]
Are you using Normalize? http://codepen.io/corysimmons/pen/ZYNBba

Opened an issue about this a week ago. Feel free to chime in. https://github.com/necolas/normalize.css/issues/427

**Comment by mooror** [comment]
Thank you sir. That did the trick. Cheers

**Comment by corysimmons** [comment]
:+1:
