### ISSUE TITLE
Change syntax from block() to column(), row(), and waffle()

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/lost#54]
This would be an easy change. I'm hoping to get some community feedback though.

Basically the change would be changing code like this:

```stylus
.foo
  block('1/3', column)
  @media (min-width: 800px)
    block('1/2')
  @media (min-width: 1100px)
    block('1/3', both)
```

...to code like this:

```stylus
.foo
  row('1/3')
  @media (min-width: 800px)
    column('1/2')
  @media (min-width: 1100px)
    waffle('1/3')
```

Personally I think it looks better and is more readable, but I want to get community feedback. Obviously this would be a major version bump up to `5.0.0`.

**Comment by flip4bytes** [comment]
I have personally never been a big fan of having too many variables. Using mixins instead definitely look better. Though it is nice just having block always be the primary mixin.

I think a lot of people are used to using `col()` / `column()` on things like bootstrap and other grid systems. Especially on the competing Jeet preprocessing grid system. I think that more people will be comfortable with it and willing to come over simply by making this as similar as possible but just produce better code and have more functionality (like it does).

So part of me says keep it `block()` but the other part of me likes how descriptive `row()`, `column()`, and `waffle()`. The second code is definitely more readable. I'm torn though, would really like to hear what others have to say about this.

**Comment by corysimmons** [comment]
I'm playing around with it now and definitely enjoy the new syntax better. Gonna go ahead and implement and just hope everyone is happy with it.

**Comment by stolinski** [comment]
I like it. I agree that people are used to col/column.

**Comment by corysimmons** [comment]
:+1:

**Comment by corysimmons** [comment]
Should be done in about 30 mins.

**Comment by corysimmons** [comment]
- [ ] Stylus
- [ ] SCSS
- [ ] LESS

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/b2cc4be1ee2cc37dada7a96b24017368724c2719

**Comment by dmitrykiselyov** [comment]
I tried It and I liked It :+1:

**Comment by corysimmons** [comment]
@dmitrykiselyov IKR! I've been toying with it all night and it just feels better. As an added bonus it broke up that huge `block()` mixin so now it's much more maintainable/extendable. =)

**Comment by dbox** [comment]
Is this still the case or do I have to use `lost-column` ?

**Comment by corysimmons** [comment]
@dbox Since 6.0.0 you need to use `lost-column`, `lost-row`, `lost-waffle`.

**Comment by dbox** [comment]
For namespacing reasons? Will def miss col() ...

**Comment by corysimmons** [comment]
Yeah for namespacing. I miss `column` and such too, but we don't want to step on W3C's toes when they add some `column` property yknow?

**Comment by dbox** [comment]
So just my .02:

Even being familiar with Jeet, it took me a few seconds to realize what Lost was. If I'm going to be using this with my team, and the first thing they see is `lost-column`, they are going to be confused. In fact, it almost says the opposite of what it is really doing. I know we can easily set up some aliases internally, but then when someone goes to the lost docs it will still be in those names. Not the end of the word, but not ideal.

And, you won't want to hear this, but if mass-adoption is an end goal (which, maybe it's not), I'm not sure Lost is the best name. IMHO, I would go with something like Lattice, which hints hints at columns, rows, waffle, and of course being the structure for the real product to grow from. Obviously, just an example, but, names are important! (But... just imagine that sweet logo with a small leaf starting to grow out :smile:  )

Please don't take this as negative. You've done *incredible* job with this, and I can't wait to use it (with some name changes – either internally or officially).

Maybe, at the very least, it'd be good to include some aliases for old-schoolers.

Thanks again for all the hard work, and I'd be happy to help out where I can, whether it be on the site or something else.

**Comment by corysimmons** [comment]
I agree but I already named it Lost so I think we're stuck with it. :dancer: 

I don't understand your point about `lost-column` not representing what it actually is? They are definitely columns within a row (just like every other grid system names them).

Even the Jeet team is going to start namespacing as some of Jeet's stuff started conflicting with CSS syntax (`center` for instance). So far as aliasing, I'm kind of against aliasing in general nowadays. It makes it so half the users are doing it one way, and the other half are doing it another way - even the Stylus team is going to start locking their syntax I think because this really divides up the developer community when you give them syntax preferences. Also, the aliases might conflict with CSS spec in the future so aliasing `lost-column` as just `column` would probably break in the future.

**Comment by dbox** [comment]
I just meant that literally a lost-column sounds like something that used to be a column but now it's lost.

**Comment by corysimmons** [comment]
Oh I see. Hopefully people can figure it out. :dancers:

**Comment by dbox** [comment]
okie dokie. I'll keep lattice for myself. :smile:  :dollar:

**Comment by dbox** [comment]
If I'm using lost with stylus how would I do the aliases?

`lost-column = col` doesn't work as usual.

**Comment by corysimmons** [comment]
Are you using the PostCSS version of Lost with Stylus or are you using an old version of Lost?

**Comment by dbox** [comment]
Postcss

**Comment by corysimmons** [comment]
`col = lost-column: 1/2` wouldn't work since Stylus needs something like a mixin to alias.

Try:

```stylus
grid($x)
  lost-column: x

col-third = grid(1/3)
```

It might work but Stylus might error out as well.

**Comment by dbox** [comment]
https://github.com/seaneking/postcss-alias

maybe this?

**Comment by corysimmons** [comment]
Yeah. But tbh, it seems like another level of abstraction you don't need.

**Comment by dbox** [comment]
you dont know how much i want to just say `col` haha

**Comment by corysimmons** [comment]
ha, then yeah postcss alias looks like it'll do the job.
