### ISSUE TITLE
CodePen doesn't work with LESS version

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/lost#57]
CodePen cuts the units off of values in the `calc()` expressions thereby making sizing break. I'll sent an email to their support. Until this is addressed, CodePens for LESS won't work.

**Comment by corysimmons** [comment]
Reduced test case: http://codepen.io/corysimmons/pen/yyWZVX

**Comment by dmitrykiselyov** [comment]
Weird LESS, 3rem works fine. 
The CodePen is not guilty, it is a [LESS bug](https://github.com/less/less.js/issues/974) or a feature :smile:

**Comment by dmitrykiselyov** [comment]
```less
width: ~"calc(100% - @{foo})"; 
```

**Comment by corysimmons** [comment]
Why does the same code work locally for Lost but not on CodePen though?

http://codepen.io/corysimmons/pen/pvmwQm

**Comment by dmitrykiselyov** [comment]
Yes, you are right, locally is working. The CodePen is GUILTY :fire: 
I thought you meant problem with this `calc(100% - @foo);`
Your [second example](http://codepen.io/corysimmons/pen/pvmwQm) is more specifically highlights the problem.

**Comment by corysimmons** [comment]
lol dat fire :pitchfork:

**Comment by corysimmons** [comment]
Yay CodePen fixed it. There support is stellar.
