### ISSUE TITLE
Grid systems comparision

### ISSUE THREAD

**Issue by norin89** [corysimmons/lost#60]
In your comparison you wrote that only Lost grid has "No Additional Ratio Context" what's not really true. E.g in Bootstrap you don't need additional context - [Bootstrap Grid Nesting](http://getbootstrap.com/css/#grid-nesting), same as Foundation. I don't know what about other non "on-the-fly grids" but I assume it's the same - because of no real gutters. If that was the reason you should at least mark it as "N/A". Exactly the same situation with "Consistent Horizontal Gutters".

The other thing is "Lightweight" feature. Most of the grids are described as lightweight, and most aren't. What was the comparison criteria? The questions in description make me consider Lost as not lightweight. Yes, it's source code is readable but the output code is not - with tons of `:nth-child()` pseudo-selectors it completely unreadable to humans, there is overriding of dozen CSS rules and finally output CSS for that simple demo you've prepared is really bloated. You should define some fair criteria or at least description why only Lost grid in lightweight.

Screenshot from Firefox DevTool on demo page:
![lost-css](https://cloud.githubusercontent.com/assets/7902324/7051388/4ed541bc-de28-11e4-8397-1ffca6ff328d.PNG)

Please, don't understand me wrong - I don't say Lost grid is bad. I like your solution and if browser support for `calc()` would be better I would definitely give it a try.

**Comment by corysimmons** [comment]
> In your comparison you wrote that only Lost grid has "No Additional Ratio Context" what's not really true. E.g in Bootstrap you don't need additional context - Bootstrap Grid Nesting, same as Foundation.

> Exactly the same situation with "Consistent Horizontal Gutters".

You're right, I didn't consider this and will update the comparison table.

> Most of the grids are described as lightweight, and most aren't. What was the comparison criteria?

https://github.com/corysimmons/lost/wiki/Comparison-Explanation#lightweight

So far as the demo being lightweight, you picked the example with 3 media queries that have to override each other to take a screenshot of. Here's an example with no media queries:

![](http://i.imgur.com/PKZzYbp.png)

**Comment by corysimmons** [comment]
Updated the Comparison Table to reflect Bootstrap and Foundation don't require additional context, and updated the description on Lightweight.
