### ISSUE TITLE
Port to PostCSS

### ISSUE THREAD

**Issue by IbnSaeed** [corysimmons/lost#63]
Hello 
Since this is a new project, are there plans on using Lost with Rework or postcss specifically for speed ?

**Comment by corysimmons** [comment]
I'm actually heavily considering porting Lost to PostCSS. I really like the idea of PostCSS and would love to learn more about it.

**Comment by corysimmons** [comment]
@IbnSaeed Would love some help getting familiar with PostCSS. I'm a total newb to it and it's docs aren't super friendly.

**Comment by corysimmons** [comment]
Yeah I'm working on this now. This will be the next big thing for Lost and help me consolidate all these preprocessors down to one codebase/syntax.

I'm an idiot so it might take a while, but I'll definitely try my hardest to get it.

**Comment by corysimmons** [comment]
Very happy if people want to pitch in on this port. =)

**Comment by IbnSaeed** [comment]
How can i help ?

**Comment by corysimmons** [comment]
@IbnSaeed They just answered my question [here](https://github.com/postcss/postcss/issues/293) which cleared up some things. I might be able to get this on my own now, but if I run into problems I'll ping you to jump in. =)

**Comment by corysimmons** [comment]
- [ ] PostCSS port ([help](https://github.com/postcss/postcss/issues/293))
- [ ] Grunt plugin ([example](https://github.com/nDmitry/grunt-autoprefixer))
- [ ] Gulp plugin ([example](https://github.com/sindresorhus/gulp-autoprefixer))
- [ ] Stylus plugin ([example](https://github.com/jenius/autoprefixer-stylus))

Missing anything?

**Comment by IbnSaeed** [comment]
Excellent. 

How about doing it with npm scripts instead of relying on Grunt and Gulp ? less dependencies

**Comment by corysimmons** [comment]
We can do it with all of the above. =)

**Comment by mestaritonttu** [comment]
Regarding npm scripts: https://github.com/keithamus/npm-scripts-example

**Comment by corysimmons** [comment]
Ah thanks @mestaritonttu 

I'll try to get to work on this sometime this week. Thanks for the help everyone.

**Comment by teddybradford** [comment]
:+1:

I've been trying out PostCSS and am really liking how modular it is. Excited for the Lost port!

**Comment by corysimmons** [comment]
I'm making a lot of progress with this. This will definitely happen. Syntax will look like:

```css
.foo {
  column: 2/6;
  cycle: 3;
  gutter: 60px;
}
```

For all 3 preprocessors and pure CSS (with the help of Grunt/Gulp).

**Comment by corysimmons** [comment]
This will also put on display my absolutely disgusting JS skills so I'm begging anyone who is great at JS to refactor the code once it's up.

**Comment by teddybradford** [comment]
That's great to hear, Cory! Can't wait to try it out.

I would recommend namespacing with `lost-` rather than `l-` or none for a couple of reasons:

1. To avoid any confusion with other CSS properties (such as `columns`).
2. To make visual grouping of Lost-specific properties easier when looking at a selector with lots of properties (i.e., being about to see immediately where all the `lost-` properties are located within a list of other properties).
3. Future-proof.
4. Convention to used namespacing for grids already established with `flex-` properties.
5. Reinforces the Lost brand as a grid system.

The only downside that I see is that it's slightly more verbose, but I think the benefits of using a `lost-` namespace outweigh that potential negative (and I personally prefer the slightly more verbose version anyway due my listed reason 2).

**Comment by corysimmons** [comment]
@teddybradford These are great reasons and as a result we'll namespace with `lost-`. Thanks for your help!

**Comment by flip4bytes** [comment]
Good points @teddybradford, I agree!

**Comment by corysimmons** [comment]
- [ ] edit
- [ ] clearfix
- [ ] flex-container
- [ ] center
- [ ] align
- [ ] column
- [ ] row
- [ ] waffle
- [ ] offset
- [ ] move
- [ ] masonry-wrap
- [ ] masonry-column
- [ ] get-size

**Comment by IbnSaeed** [comment]
@corysimmons Can you point to the code you are working on inside Lost for PostCSS.

**Comment by corysimmons** [comment]
@IbnSaeed I'd prefer not to mess around with merge conflicts right now, and I'm making pretty good progress on it. Let me get it to a good place then I'll push it to a dev branch.

**Comment by IbnSaeed** [comment]
excellent

**Comment by corysimmons** [comment]
At this point I think I understand PostCSS well enough to do this. Made some helper functions and it's going by pretty quick. Just a ton of busy work. =[

**Comment by corysimmons** [comment]
Adding long hand and short hand syntax.

**Comment by IbnSaeed** [comment]
any examples ?

**Comment by corysimmons** [comment]
```stylus
.foo
  lost-column: 1/2 60px flex

.bar
  lost-column: 1/2
  lost-column-gutter: 60px
  lost-column-flexbox: true
```

**Comment by teddybradford** [comment]
What is the benefit of having gutter and flexbox properties as sub-properties of `lost-column-`? Is there ever an instance where you can have `lost-column-gutter` and `lost-row-gutter` on the same selector?
 
Unless I've overlooked something, I think this would be nicer to work with:

`lost: [column|row|waffle ratio gutter flex …]` (shorthand)
`lost-edit: [true|false]` (maybe `lost-draft` instead?)
`lost-clearfix: [true|false]`
`lost-flex: [true|false]`
`lost-center: [...]`
`lost-align: [...]`
`lost-column: [ratio]`
`lost-row: [ratio]`
`lost-waffle: [ratio]`
`lost-offset: [...]`
`lost-move: [...]`
`lost-masonry: [column wrap]` (shorthand)
`lost-masonry-column: [...]`
`lost-masonry-wrap: [...]`

I especially like the shorthand `lost: column 1/2 60px flex`.

**Comment by teddybradford** [comment]
I'm not really set on the syntax I've proposed either, I just wanted to put something out so we could all discuss it.

**Comment by corysimmons** [comment]
Yes there are times when you could have both `lost-column-gutter` and `lost-row-gutter` (e.g. you want bigger gutters for your vertical grid than your horizontal grid).

So far as `clearfix` and `edit`, I've put those into `lost-utility`.

I'm offering shorthand syntax as well as long hand. So you can write like:

```stylus
.foo
  lost-column: 1/2
  lost-column-gutter: 60px
  lost-column-flexbox: flex
```
or
```stylus
.foo
  lost-column: 1/2 60px flex
```

So far as your even shorter shorthand of just `lost`, it seems like `lost-column` is the same thing. For instance look at them both:

```stylus
.foo
  lost-column: 1/2 60px flex

.foo
  lost: column 1/2 60x flex
```

The difference is I would expect `lost` to operate on every single grid function as well so I can see people trying:

```stylus
.foo
  lost: clearfix
  lost: move 1/2
```

I'd prefer to be a bit more explicit with `lost-mixin` since it's just one character more and a bit less confusing.

**Comment by teddybradford** [comment]
Ah, okay. That makes total sense now. I have no issues with your approach after that clarification. :smile_cat:

**Comment by corysimmons** [comment]
https://github.com/corysimmons/lost/tree/cs/post-css if anyone is interested. I'm sure it needs a ton of refactoring.

**Comment by corysimmons** [comment]
I'll get to work on the Grunt/Gulp/Stylus/NPM plugins tomorrow.

**Comment by teddybradford** [comment]
Nice job! This is exciting. My initial thought is that `lost-utility` seems out of place (not specific enough I guess); I can't think of an example of something similar to it in vanilla CSS. I'll take a closer look at it tomorrow, but it looks really great from a quick glance! :+1:

**Comment by corysimmons** [comment]
@teddybradford Yeah I'm not super fond of it but I couldn't figure out a way to call mixins on a root level y'know?

Like...

```css
.foo {
  clearfix;
}
```

...looks pretty weird to me.

**Comment by teddybradford** [comment]
How about something like this?

```css
.foo {
  lost-mode: edit; /* Personally I still prefer "draft" rather than "edit"; it seems more apt */
  lost-clear: children; /* Clearfix */
}

**Comment by corysimmons** [comment]
But those would be the only options for those.

**Comment by teddybradford** [comment]
Is that necessarily a bad thing? It would allow for more options in the future, such as more nuanced draft modes (only rows or only columns, for example).

**Comment by corysimmons** [comment]
I've considered this but I don't think they would have any possibilities in the future. For instance, I can't think of a way to make `edit` only work with rows or columns. `clearfix` will never accept any options. Etc.

I think the rule of thumb is if it doesn't accept any options it's a utility.

**Comment by teddybradford** [comment]
Hmm, okay. I suppose then `lost-utility` does seem like the best option for now.

**Comment by corysimmons** [comment]
Also, for anyone interested in helping out, the port still needs:

- [ ] Refactoring
- [ ] Lots of testing
- [ ] Packaging
  - [ ] npm
  - [ ] Grunt
  - [ ] Gulp

**Comment by teddybradford** [comment]
I'm going through the code now to see if I can get it working in my gulp workflow.

**Comment by corysimmons** [comment]
@ai suggests I look at https://github.com/postcss/postcss-mixins for packaging.

**Comment by corysimmons** [comment]
@teddybradford You probably won't be able to get it working in Gulp since it's not really packaged for Gulp or Grunt or *anything* yet.

**Comment by teddybradford** [comment]
@corysimmons I made a few modifications and got it working with `gulp-postcss`.

**Comment by corysimmons** [comment]
@teddybradford Awesome, can you show me?

**Comment by corysimmons** [comment]
Also, I'm in https://gitter.im/corysimmons/lost if you want to carry this over there.

**Comment by teddybradford** [comment]
@corysimmons Sure thing!

**Comment by corysimmons** [comment]
Closing for smaller issues.
