### ISSUE TITLE
Plans for working with jss?

### ISSUE THREAD

**Issue by serapath** [corysimmons/lost#65]
[jss](https://github.com/jsstyles/jss)

**Comment by corysimmons** [comment]
I haven't taken a look at JSS yet but I'll leave this open and look at it and see if it's something we might do.

**Comment by serapath** [comment]
thx, that would be neat :-)

**Comment by corysimmons** [comment]
Also if you're familiar with JSS and would like to start a port on this I'd be ecstatic. =)

**Comment by serapath** [comment]
I currently use a project called [atomify](https://github.com/atomify/atomify) to be able to have `@import` in css working the same way as `require` in commonJS. That way, my components, using BEM conventions, could contain their own css and assets and be installed with `npm install` into `node_modules` ...

... I'm just now switching slowly to `jss`, because I gave up on SSR (server side rendering) and (virtual dom), instead I believe the future will be like operating systems that receive updates for installed software all the time, thus maybe something like [hyperboot](http://hyperboot.org/)

JSS gives me the full power of javascript and I see how this plays well with javascript controlled animations.

I was using `jeet` and `stylus` in the past, then switchted to `reworkcss + plugins`, which is also what `atomify` is using. I will look into `lost` and I actually might try something, but it might need a lot of time, before I feel comfortable enough doing that :-)

**Comment by corysimmons** [comment]
No problem. I'll leave this open. First on my list would be porting to PostCSS.

**Comment by serapath** [comment]
Why PostCSS rather than reworkcss?

**Comment by corysimmons** [comment]
I'm not sure. What's the difference between the two?

**Comment by serapath** [comment]
I dont know. Wasn't clear to me after reading:
http://nicolasgallagher.com/custom-css-preprocessing/
https://github.com/postcss/postcss/issues/64
https://github.com/postcss/autoprefixer/issues/163

**Comment by corysimmons** [comment]
Yeah it's not clear to me either. Seems like they are at odds with each other though?

**Comment by corysimmons** [comment]
It seems they both generally do the same thing but maybe PostCSS is maintained a bit better (last update several hours ago vs. Rework's Feb. 1) with a lot more commits, so I'd say it's a stronger project and is probably better than Rework as a result.

TBH I'm not sure what the point in porting to all these different things is but I've been itching to learn more about Rework/PostCSS so I'm using this as an opportunity to do so.

**Comment by serapath** [comment]
I was using `stylus + rupture + nib + jeet` for a long time.
Then i switched to `atomify` (which includes rework), so I can use different "rework plugins" to get my custom pre/post-processor, but mainly to get "node require" like `@import` statements in css to make nice components.

Now I started to investigate `animation libraries` a bit more and currently explore `velocity.js` and figured out, I'll basically find myself setting "css" in my "javascript files" a lot of times, so why not start there in the first place and use `jss` :-) So that's what I'm exploring now...

**Comment by corysimmons** [comment]
That would make a really interesting library. Be sure to ping me if you ever release something.

**Comment by corysimmons** [comment]
Actually I think I'm going to put all my eggs into the PostCSS route instead of JSS as well. Would love to see a port if you're interested though.

**Comment by serapath** [comment]
I would be interested in your reasoning for that :-)
How do you imagine the workflow for building a component based app?

**Comment by corysimmons** [comment]
Sorry I didn't get back to you sooner - saw this email while I was out and about and forgot to reply.

I'd like to get Lost down to one codebase (PostCSS).

I'm picking Post because it seems like the most well maintained, powerful, and popular of the options. 

I'm not sure what you mean about the workflow thing.

**Comment by serapath** [comment]
How would i create a visual `npm install`able component, that uses `lost`?

Maybe I can write some "pseudo-component"
```js
// [projectX/SOURCE/index.js]

var // DEPENDENCIES
    articleComponent = require('article'),               // [projectX/node_modules/article/...]
    productGrid      = require('lost-productGrid'),      // [projectX/node_modules/lost-productGrid/...]
    styling          = require('./index.css'),           // [projectX/SOURCE/index.css]
    template         = require('./index.template.html'); // [projectX/SOURCE/index.template.html]

module.exports = Component_projectX;

function Component_projectX (container, params) {
  var args =  {
        title : params.title || 'unknown',
        data  : params.data  || []
      },
      TMP = (TMP=document.createElement('div'),TMP.innerHTML=template,TMP.childNodes[0]),
      __title  = TMP.querySelectorAll('.ProjectX__title')[0],
      __grid   = TMP.querySelectorAll('.ProjectX__grid')[0],
      titleAPI = function (newTitle) { __title.innerHTML = newTitle; },
      gridAPI  = productGrid(__grid, {
        data   : args.data,
        item   : articleComponent
      });

  titleAPI(args.title);
  container.innerHTML = __.innerHTML;
  var api = {
    titleAPI: titleAPI,
    gridAPI : gridAPI
  };
  return api;
}
```
A component consists of **html**, **css**, **javascript** and **assets**.
They can be installed via `npm install componentName`.
This "pseudo-component" written above uses two components.
* `var articleComponent = require('article');`
* `var productGrid      = require('lost-productGrid'):`

The `articleComponent` is "dependency-injected" into the `productGrid` component.
The `projectX` component adds a `title` to that "mashup" and exports itself as a freshly composed component.

If I would use some animations, I could even import the css and use it as a starting point when doing animations using someting like [velocity-animate](https://github.com/julianshapiro/velocity).

# Problem

Once I do it like above, whenever components are installed via `npm`, they get nested into the `/node_modules/` folder. It's not at all problematic when it comes to `javascript`, because the `require(...)` function resolved the correct paths and [browserify](http://browserify.org/) can create a `bundle.js` that can be injected into the browser.
**BUT:**
It is a problem when it comes to CSS, especially when it comes to `asset paths` (fonts, images, ...).
The `@import` does not work in the same way `require(...)` works, so it will not easily find the css files nested into some deeply nested `node_modules` folders depending on the component.
Even worse, the asset paths are relative to each component and once bundled via a `browserify for css` the `asset paths` would STILL be wrong.

# Solution
My current solution is to use [atomify](https://github.com/atomify/atomify), because beside css `@import url(...);`, you can also write `@import "componentName";` which will find the `/node_modules/../../componentName/` and check `package.json` for an `css entry file` and grab it.
In addition it will check all the `assets` (fonts/images/...) referenced in either the `css file` or the `html template file` of that component, copy them to a `/BUILD` folder and adapt all the `asset paths` accordingly, so that it will JUST WORK :-)

Atomify uses [reworkCSS](https://github.com/reworkcss/rework), so you can use all kinds of custom plugins to define your own `css (pre/post)processor`. Atomify will work "recursively", so if you run the `build` or `watch` task on "projectX", it will pick up configuration from `dependency components` and run `atomify` on them too. **THIS IS TRICKY TO DO WITH `stylus` or `sass` or `postcss`** because it's not supported and I am not aware of such a "re-usable component driven approach" when using them.

That's all nice, because I can use `npm` to install self contained re-usable components without any manual copying, **but:**
* when I start to use animation libraries, like `velocity-animate`, I would like to have access to my CSS from javascript, so I would prefer `JSS` (which would allow me to use browserify+transforms and get rid of additional css pre/post processors).

**Comment by corysimmons** [comment]
Thanks for the lengthy explanation. After I get the PostCSS port done I might revisit this. Also, this seems way above my level of CSS/JS skill, so again, if you want to undertake this mission I would definitely link to your port in the README.

**Comment by serapath** [comment]
The problem is, that the css grid skills necessary to understand how exactly lost or even jeet works, is way way beyond my skill level, so it would be a very daunting task :-)
I guess I first will try to get some more familiarity with `jss` and figure out my workflows and then later revisit `lost`.

**Comment by corysimmons** [comment]
All the code is already here and I can help you out with any questions you might have along the way.
