### ISSUE TITLE
Adding Singularity.gs to Comparison table 

### ISSUE THREAD

**Issue by IbnSaeed** [corysimmons/lost#68]
Hello @corysimmons 

Is it possible to add Singularity in the comparison table ?

**Comment by corysimmons** [comment]
I think the comparison table is big enough and, to be honest, I don't know enough about Singularity to give it a solid breakdown. I imagine it's very similar to Susy though so far as features.

**Comment by corysimmons** [comment]
Plus I kinda like Scott Kellum and don't want to look like I'm stinking on his grid. =)
