### ISSUE TITLE
Codekit

### ISSUE THREAD

**Issue by custa1200** [corysimmons/lost#69]
This is not showing up as a component in the CodeKit application's bower area. :(

**Comment by corysimmons** [comment]
Where can I view this at?

**Comment by custa1200** [comment]
https://incident57.com/codekit/ is the app. I go to it's components section which is supposed to be bower and type "lost-" in the search bar and see no results.

**Comment by corysimmons** [comment]
Did it exist before and now it's missing or something? If I understand correctly, Bryan (the maintainer of CodeKit) has to manually add/maintain packages. Was Lost in CodeKit at one point?

**Comment by custa1200** [comment]
No I have never seen it, I only came across this project today (I had been using Jeet, which in itself was pretty cool). I thought the power of bower was that it was just seamless as developers add their packages to a central repository. It would be crazy to try to manage 1000's of packages manually I would have thought.

**Comment by corysimmons** [comment]
Yeah it does seem pretty intense. I was talking to Bryan about adding Lost to CodeKit but I'm not sure if he has yet or not. Let me get the PostCSS port out and then I'll message him about it.
