### ISSUE TITLE
Does align() not work similar to Jeet

### ISSUE THREAD

**Issue by custa1200** [corysimmons/lost#71]
Does an align() element need to be sitting inside a column to function? Using lost as a drop in replacement for Jeet does not seem to align as instructed.

**Comment by corysimmons** [comment]
Lost is definitely not a drop-in replacement for Jeet, but `align()` actually should work rather similarly. `align()` just needs to be applied to any parent element, and a child element will be aligned accordingly.

**Comment by custa1200** [comment]
Ahh I was applying it to the child. I will try in the morning.

**Comment by corysimmons** [comment]
:+1:
