### ISSUE TITLE
Alignment mixin

### ISSUE THREAD

**Issue by mydudechris** [corysimmons/lost#72]
What would I do about something like this? 

http://cl.ly/image/11321p000W0M
http://cl.ly/image/0I0A3H0Q3a0n

section > div*5 > div > h2 + p

I want to create a grid of responsive squares that have vertically aligned/centered content within them. I'm using the align mixin on the section > divs which each contain a div.child with content. I've applied align() to the section div parent and it looks like everything within is being aligned. My expectation is that only the element preceding the containing parent is aligned. I.E.

section > div*5 > div (is aligned) > h2 + p (isn't aligned unless I say so)

Thanks!

**Comment by corysimmons** [comment]
http://codepen.io/corysimmons/pen/zxgvXg?editors=110 like so?

**Comment by mydudechris** [comment]
Hmm, I must've missed something. Thanks @corysimmons

**Comment by corysimmons** [comment]
No problem. Let me know if you have any more questions.
