### ISSUE TITLE
align(reset)

### ISSUE THREAD

**Issue by mydudechris** [corysimmons/lost#73]
position: relative;
    > * {
        position: absolute;
        @if ($location == reset) {
        top: auto;
        right: auto;
        bottom: auto;
        left: auto;
        transform: translate3d(0, 0, 0);

I assume the reset value would be used when you want to stop aligning elements, say for mobile, right? If that's the case, shouldn't that position absolute become relative?

**Comment by corysimmons** [comment]
Indeed. Good eye. Will fix.

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/bfe2bd2347ae4a9cddb643200a5dce01a11c60ed

**Comment by mydudechris** [comment]
You're the man, thanks!

**Comment by corysimmons** [comment]
:+1:
