### ISSUE TITLE
Align & Translate3D = blurry text in Chrome

### ISSUE THREAD

**Issue by mydudechris** [corysimmons/lost#77]
I've had to revert to using the 2D transform version instead of the 3D because all my text elements within aligned elements become super blurry while in Chrome. I've tried applying transform-style: preserve-3d; to the parent elements to no avail :(

**Comment by corysimmons** [comment]
I'll remove the 3d stuff for the PostCSS port.

**Comment by mydudechris** [comment]
Will that be available for the scss version or are you dropping that?

**Comment by corysimmons** [comment]
I'm dropping the Stylus, SCSS, and LESS versions.

The new version will let you use the same syntax for **any** preprocessor **and** CSS.

Think of it like Autoprefixer except for grid systems. You include it in your pipeline with Grunt or Gulp, and then write syntax like this:

```scss
.foo {
  lost-column: 1/3;
  lost-align: right;
  background: red;
  padding: 30px;
}
```

**Comment by corysimmons** [comment]
By doing this it will be available to more people, with the same exact beautiful syntax, and I won't have to maintain 3 different codebases.

**Comment by mydudechris** [comment]
:+1:

**Comment by jakecleary** [comment]
@corysimmons that's sick! What resources are you using to learn that?

**Comment by mestaritonttu** [comment]
The future is bright :sunglasses:

**Comment by corysimmons** [comment]
@jakecleary https://github.com/postcss/postcss/blob/master/API.md and a lot of trial and error. :(

@mestaritonttu haha

**Comment by corysimmons** [comment]
I also forget why we're operating on the parent container with `position: relative;` and the child container with `position: absolute;`. I remember I did this for a reason but can't remember why exactly...

`position: relative;` on the child container seems to work fine and I very well might change it to this (although it might jack up `flex`).

http://codepen.io/corysimmons/pen/bNXKXe?editors=110

**Comment by jakecleary** [comment]
@corysimmons remember we did some tests for Jeet and we found that it caused issues when the element shared a space with other elements.

**Comment by corysimmons** [comment]
Ah, okay. Thanks.

**Comment by custa1200** [comment]
I hope that CodeKit gets updated to use PostCSS, this does sound quite exciting.

**Comment by jakecleary** [comment]
@corysimmons Np.

@custa1200 have you tried using something like Gulp in the mean time? I'd be happy to show you a working file that you could drop into a project.

**Comment by corysimmons** [comment]
Closing as this is fixed in the PostCSS port which will be live in a couple days (maybe tonight depending on how quick I can make these Gulp/Grunt/Stylus plugins).

**Comment by custa1200** [comment]
So does that mean that the PostCSS port will somehow work seamlessly with current Stylus setups?

**Comment by corysimmons** [comment]
It won't work seamlessly but it will still work with any preprocessor (and pure CSS). You'll need to change all your mixins to use the PostCSS port syntax so:

```stylus
.foo
  column('1/2')
```

...becomes...

```stylus
.foo
  lost-column: 1/2
```

**Comment by custa1200** [comment]
I'd be happy with that. :)

**Comment by EnMod** [comment]
@custa1200 Just to add to this, I got Stylus working with DocPad rendering my `.styl` files and having PostCSS process the style.css that docPad generates.  Using the syntax Cory suggested all my stylus mixins went through easily.  

The exception was `center()` with no arguments, which obviously can't be called as `lost-center:` and rendered properly...then again I never just tried using `lost-center:;` to see if that would work lol. Logically, it should...right?

**Comment by corysimmons** [comment]
@EnMod Are you saying you wrote your own PostCSS port or are you just talking about using Lost v6?

**Comment by EnMod** [comment]
Just talking about using Lost v6 and describing how I worked it into my Stylus workflow.  Thought it would be a good idea to add that to this conversation, for others who may be reading and wondering how to do the same.

**Comment by corysimmons** [comment]
Ah I see.

`lost-center` doesn't have a default value. I think the best way to do something like that would be:

```stylus
$center-default = 1140px

.foo
  lost-center: $center-default
```

**Comment by EnMod** [comment]
Ah good point, thanks for the insight!  Going to really enjoy Lost v6 :D

**Comment by corysimmons** [comment]
:+1: :D
