### ISSUE TITLE
Create Grunt instructions

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/lost#97]
I don't know Grunt very well so I'd love it if someone could pitch in on this.

**Comment by alexyans** [comment]
I could give a hand. Do you just want to have the same Gulp tasks performed with Grunt as an alternative, or is it something else you have in mind?

**Comment by corysimmons** [comment]
@alexyans Awesome! The same task would be great.

**Comment by corysimmons** [comment]
Fixed https://github.com/corysimmons/lost/commit/75db55ab7ec1e21a54c566f23f4ba888664e5747

**Comment by corysimmons** [comment]
@alexyans Feel free to PR if you know of a way to support watching/compiling multiple files and/or sourcemaps.
