### ISSUE TITLE
Brunch instructions

### ISSUE THREAD

**Issue by dmitrykiselyov** [corysimmons/lost#99]
##### Brunch

- Install [NodeJS](http://nodejs.org)
- Install [Brunch](http://brunch.io/) `npm install -g brunch`
- Create a new Brunch project `brunch new https://github.com/brunch/dead-simple`
- Install [PostCSS](https://www.npmjs.com/package/postcss-brunch) `npm install --save LaurentTreguier/postcss-brunch`
- Install [Autoprefixer](https://www.npmjs.com/package/autoprefixer) `npm install --save autoprefixer`
- Install [Lost](https://www.npmjs.com/package/lost) `npm install --save lost`
- Update `brunch-config.coffee`
```coffee
exports.config =
  # See http://brunch.io/#documentation for docs.
  files:
    javascripts:
      joinTo: 'app.js'
    stylesheets:
      joinTo: 'app.css'
    templates:
      joinTo: 'app.js'
  plugins:
    postcss:
      config: (postcss) ->
        postcss().
        use(require('autoprefixer')(['last 1 versions']).postcss).
        use(require('lost').postcss)
```

- Run `brunch watch`

This will watch your app/style.css file for any changes and then process it with Autoprefixer and Lost Grid (which will convert Lost Grid rules into vanilla CSS code), and output the processed CSS to public/app.css.

**NOTE:** postcss-brunch has [issue](https://github.com/iamvdo/postcss-brunch/issues/3), but with this [fix](https://github.com/iamvdo/postcss-brunch/pull/2) is ok, but will work only with a vanilla CSS and Less.

**[⬆ back to top](#table-of-contents)**

&nbsp;

**Comment by corysimmons** [comment]
Thanks. Can you add on to this with JavaScript (instead of Coffee) and Autoprefixer and have it watch a specific directory and output to a specific directory (to be more inline with the other instructions)?

**Comment by dmitrykiselyov** [comment]
But Brunch is different :smile: 
Config by default is coffee.
Min config:
```coffee
exports.config =
  files:
    javascripts:
      joinTo: 'app.js'
    stylesheets:
      joinTo: 'app.css'
```

**Comment by corysimmons** [comment]
Oh is Brunch heavily Coffee friendly? :)

**Comment by corysimmons** [comment]
Want to open a PR and get some GitHub commit credit?

**Comment by dmitrykiselyov** [comment]
No :smile: Just a second, please.

**Comment by dmitrykiselyov** [comment]
Ok, instruction 100% is ready :+1:

**Comment by corysimmons** [comment]
Okay, just confirming you don't want to PR?

**Comment by dmitrykiselyov** [comment]
Ok. But tommorow. It's too late.

**Comment by teddybradford** [comment]
PR https://github.com/corysimmons/lost/pull/101 merged.
This issue can be closed now.

**Comment by dacodekid** [comment]
@corysimmons, I'm completely new to Brunch (just started today), but according to [Brunch's doc](https://github.com/brunch/brunch/blob/stable/docs/faq.md#i-dont-like-coffeescript-does-brunch-work-for-pure-js-projects), you can use either 'coffeescript' or 'javascript' as your config file. Here is the closest JS to your gulp file.

```javascript
exports.config = {
    paths: {
        "public": 'dist'
    },
    files: {
        stylesheets: {
            joinTo: 'css/app.css'
        }
    },
    plugins: {
        postcss: {
            config: function(postcss) {
                return postcss()
                    .use(require('autoprefixer')(['last 1 versions']))
                    .use(require('lost'));
            }
        }
    }
}
```

**Comment by corysimmons** [comment]
Ah alright thanks.
